import {
  decimal,
  index,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  tinyint,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  /** bcrypt hash for email+password login. Null for OAuth-only users. */
  passwordHash: varchar("passwordHash", { length: 255 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Domain tables for the ERP.
 *
 * All rows are scoped by `userId` so the API can isolate each user's data.
 * Primary keys are UUID v4 strings (CHAR(36)) generated by the server on
 * create — matching the F1-06 requirement of replacing Date.now() IDs.
 *
 * Monetary values use DECIMAL(12,2) to avoid floating-point loss. Drizzle
 * exposes them as strings; the API layer converts to/from number for the
 * client which already uses `number` for `valor`/`preco`.
 *
 * Dates of business events (Pedido.data, Transacao.data) are stored as
 * ISO 8601 strings in VARCHAR (per F1-06), so any locale formatting is a
 * presentation concern.
 */

export const produtos = mysqlTable(
  "produtos",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    nome: varchar("nome", { length: 255 }).notNull(),
    categoria: varchar("categoria", { length: 64 }).notNull(),
    preco: decimal("preco", { precision: 12, scale: 2 }).notNull(),
    // ── v2 wizard extensions (additive) ───────────────────────────────────
    tipoItem: mysqlEnum("tipo_item", ["produto", "servico", "insumo"]).default(
      "produto",
    ),
    sku: varchar("sku", { length: 64 }),
    gtin: varchar("gtin", { length: 14 }),
    ncm: varchar("ncm", { length: 8 }),
    cfop: varchar("cfop", { length: 4 }),
    cest: varchar("cest", { length: 7 }),
    origem: varchar("origem", { length: 1 }).default("0"),
    unidade: varchar("unidade", { length: 6 }).default("UN"),
    precoCusto: decimal("preco_custo", { precision: 12, scale: 2 }),
    precoPromo: decimal("preco_promo", { precision: 12, scale: 2 }),
    margemLucroPercent: decimal("margem_lucro_percent", {
      precision: 5,
      scale: 2,
    }),
    controlaEstoque: tinyint("controla_estoque").default(1),
    estoqueAtual: decimal("estoque_atual", { precision: 12, scale: 3 }).default(
      "0",
    ),
    estoqueMinimo: decimal("estoque_minimo", { precision: 12, scale: 3 }).default(
      "0",
    ),
    localizacao: varchar("localizacao", { length: 120 }),
    fornecedorId: varchar("fornecedor_id", { length: 36 }),
    imagemPrincipal: varchar("imagem_principal", { length: 255 }),
    gramatura: varchar("gramatura", { length: 64 }),
    acabamento: varchar("acabamento", { length: 120 }),
    descricao: text("descricao"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_produtos_userId").on(t.userId),
    companyIdIdx: index("idx_produtos_companyId").on(t.companyId),
  }),
);

export type Produto = typeof produtos.$inferSelect;
export type InsertProduto = typeof produtos.$inferInsert;

/**
 * Customer (Cliente) entity. Orders reference customers by FK going forward,
 * while the legacy `pedidos.cliente` / `ops.cliente` string columns remain for
 * backward compatibility with Phase 1 screens.
 */
export const customers = mysqlTable(
  "customers",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    nome: varchar("nome", { length: 255 }).notNull(),
    tipo: mysqlEnum("tipo", ["PF", "PJ"]).default("PF").notNull(),
    documento: varchar("documento", { length: 20 }),
    telefone: varchar("telefone", { length: 32 }),
    email: varchar("email", { length: 320 }),
    endereco: text("endereco"),
    observacoes: text("observacoes"),
    // ── v2 wizard extensions (additive) ───────────────────────────────────
    /** Multi-papel: ["cliente","fornecedor","funcionario","transportadora"]. */
    papeis: json("papeis"),
    razaoSocial: varchar("razao_social", { length: 255 }),
    nomeFantasia: varchar("nome_fantasia", { length: 255 }),
    inscricaoEstadual: varchar("inscricao_estadual", { length: 32 }),
    indicadorIe: mysqlEnum("indicador_ie", [
      "contribuinte",
      "isento",
      "nao_contribuinte",
    ]).default("nao_contribuinte"),
    cep: varchar("cep", { length: 9 }),
    logradouro: varchar("logradouro", { length: 255 }),
    numero: varchar("numero", { length: 20 }),
    complemento: varchar("complemento", { length: 100 }),
    bairro: varchar("bairro", { length: 120 }),
    cidade: varchar("cidade", { length: 120 }),
    uf: varchar("uf", { length: 2 }),
    codigoMunicipioIbge: varchar("codigo_municipio_ibge", { length: 7 }),
    whatsapp: varchar("whatsapp", { length: 32 }),
    emailNfe: varchar("email_nfe", { length: 320 }),
    aceitaWhatsapp: tinyint("aceita_whatsapp").default(1),
    aceitaEmail: tinyint("aceita_email").default(1),
    aceitaSms: tinyint("aceita_sms").default(0),
    consentimentoData: varchar("consentimento_data", { length: 32 }),
    consentimentoIp: varchar("consentimento_ip", { length: 64 }),
    classificacao: mysqlEnum("classificacao", ["A", "B", "C", "D"]).default("C"),
    limiteCredito: decimal("limite_credito", { precision: 12, scale: 2 }).default(
      "0",
    ),
    prazoPadraoDias: int("prazo_padrao_dias").default(0),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_customers_userId").on(t.userId),
    companyIdIdx: index("idx_customers_companyId").on(t.companyId),
  }),
);

export type Customer = typeof customers.$inferSelect;
export type InsertCustomer = typeof customers.$inferInsert;

export const pedidos = mysqlTable(
  "pedidos",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    /** FK to customers; nullable for backward compat with legacy string-only rows. */
    customerId: varchar("customerId", { length: 36 }).references(
      () => customers.id,
      { onDelete: "restrict" },
    ),
    cliente: varchar("cliente", { length: 255 }).notNull(),
    produto: varchar("produto", { length: 255 }).notNull(),
    valor: decimal("valor", { precision: 12, scale: 2 }).notNull(),
    status: mysqlEnum("status", ["novo", "aprovado", "execucao", "entregue"])
      .default("novo")
      .notNull(),
    /** ISO 8601 string (e.g. "2026-05-15T16:00:00.000Z"). */
    data: varchar("data", { length: 32 }).notNull(),
    tipo: varchar("tipo", { length: 64 }).notNull().default("Venda"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_pedidos_userId").on(t.userId),
    customerIdIdx: index("idx_pedidos_customerId").on(t.customerId),
    companyIdIdx: index("idx_pedidos_companyId").on(t.companyId),
  }),
);

export type Pedido = typeof pedidos.$inferSelect;
export type InsertPedido = typeof pedidos.$inferInsert;

export const ops = mysqlTable(
  "ops",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    pedidoId: varchar("pedidoId", { length: 36 })
      .notNull()
      .references(() => pedidos.id, { onDelete: "cascade" }),
    /** FK to customers; nullable for backward compat with legacy string-only rows. */
    customerId: varchar("customerId", { length: 36 }).references(
      () => customers.id,
      { onDelete: "restrict" },
    ),
    cliente: varchar("cliente", { length: 255 }).notNull(),
    produto: varchar("produto", { length: 255 }).notNull(),
    status: mysqlEnum("status", ["fila", "andamento", "revisao", "concluido"])
      .default("fila")
      .notNull(),
    /**
     * F2-03: expanded 7-stage CV production pipeline. Nullable so the legacy
     * 4-status `status` column above remains the source of truth for the
     * simple kanban; this column powers the optional "Pipeline detalhado" view.
     */
    pipelineStage: mysqlEnum("pipelineStage", [
      "briefing",
      "arte",
      "aprovado",
      "pre_impressao",
      "impressao",
      "acabamento",
      "entregue",
    ]),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_ops_userId").on(t.userId),
    pedidoIdIdx: index("idx_ops_pedidoId").on(t.pedidoId),
    customerIdIdx: index("idx_ops_customerId").on(t.customerId),
    companyIdIdx: index("idx_ops_companyId").on(t.companyId),
  }),
);

export type OP = typeof ops.$inferSelect;
export type InsertOP = typeof ops.$inferInsert;

/**
 * Order line items. One pedido has many orderItems. Each item snapshots the
 * descricao/valorUnit at order time so subsequent edits to the produto row
 * (rename/delete/price-change) don't mutate history.
 */
export const orderItems = mysqlTable(
  "orderItems",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    pedidoId: varchar("pedidoId", { length: 36 })
      .notNull()
      .references(() => pedidos.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    produtoId: varchar("produtoId", { length: 36 }).references(
      () => produtos.id,
      { onDelete: "set null" },
    ),
    descricao: varchar("descricao", { length: 255 }).notNull(),
    quantidade: decimal("quantidade", { precision: 12, scale: 3 })
      .notNull()
      .default("1"),
    valorUnit: decimal("valorUnit", { precision: 12, scale: 2 }).notNull(),
    valorTotal: decimal("valorTotal", { precision: 12, scale: 2 }).notNull(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    pedidoIdIdx: index("idx_orderItems_pedidoId").on(t.pedidoId),
    companyIdIdx: index("idx_orderItems_companyId").on(t.companyId),
  }),
);

export type OrderItem = typeof orderItems.$inferSelect;
export type InsertOrderItem = typeof orderItems.$inferInsert;

export const transacoes = mysqlTable(
  "transacoes",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    tipo: mysqlEnum("tipo", ["receita", "despesa"]).notNull(),
    descricao: varchar("descricao", { length: 255 }).notNull(),
    valor: decimal("valor", { precision: 12, scale: 2 }).notNull(),
    /** ISO 8601 string. */
    data: varchar("data", { length: 32 }).notNull(),
    categoria: varchar("categoria", { length: 64 }).notNull(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_transacoes_userId").on(t.userId),
    companyIdIdx: index("idx_transacoes_companyId").on(t.companyId),
  }),
);

export type Transacao = typeof transacoes.$inferSelect;
export type InsertTransacao = typeof transacoes.$inferInsert;

/**
 * Expo push tokens registered by authenticated clients.
 *
 * Each (user, device) pair stores a single Expo push token. Tokens are unique
 * across the table: if the same token shows up for a different user (device
 * re-bound to a new account), we delete the previous row and insert a fresh
 * one — see `notifications.registerToken`.
 */
export const pushTokens = mysqlTable(
  "pushTokens",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    token: varchar("token", { length: 255 }).notNull().unique(),
    platform: varchar("platform", { length: 16 }).notNull(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_pushTokens_userId").on(t.userId),
    companyIdIdx: index("idx_pushTokens_companyId").on(t.companyId),
  }),
);

export type PushToken = typeof pushTokens.$inferSelect;
export type InsertPushToken = typeof pushTokens.$inferInsert;

/* ──────────────────────────────────────────────────────────────────────────
 * F2-01 / F2-02 — Comunicação Visual (CV) vertical
 *
 * Tables appended at the bottom per the parallel-agents schema isolation
 * convention. Existing tables above must NOT be touched (except the
 * additive `ops.pipelineStage` column for F2-03).
 * ────────────────────────────────────────────────────────────────────── */

export const priceTables = mysqlTable(
  "priceTables",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    material: varchar("material", { length: 120 }).notNull(),
    precoPorM2: decimal("precoPorM2", { precision: 12, scale: 2 }).notNull(),
    acabamentoExtra: decimal("acabamentoExtra", { precision: 12, scale: 2 })
      .notNull()
      .default("0"),
    /** 0/1 boolean — Drizzle MySQL has no native boolean. */
    ativo: tinyint("ativo").notNull().default(1),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_priceTables_userId").on(t.userId),
    companyIdIdx: index("idx_priceTables_companyId").on(t.companyId),
  }),
);

export type PriceTable = typeof priceTables.$inferSelect;
export type InsertPriceTable = typeof priceTables.$inferInsert;

export const quotes = mysqlTable(
  "quotes",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    customerId: varchar("customerId", { length: 36 }).references(
      () => customers.id,
      { onDelete: "restrict" },
    ),
    titulo: varchar("titulo", { length: 255 }).notNull(),
    validadeDias: int("validadeDias").notNull().default(7),
    status: mysqlEnum("status", [
      "rascunho",
      "enviado",
      "aprovado",
      "rejeitado",
      "convertido",
    ])
      .notNull()
      .default("rascunho"),
    valorTotal: decimal("valorTotal", { precision: 12, scale: 2 })
      .notNull()
      .default("0"),
    observacoes: text("observacoes"),
    pdfKey: varchar("pdfKey", { length: 255 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_quotes_userId").on(t.userId),
    customerIdIdx: index("idx_quotes_customerId").on(t.customerId),
    companyIdIdx: index("idx_quotes_companyId").on(t.companyId),
  }),
);

export type Quote = typeof quotes.$inferSelect;
export type InsertQuote = typeof quotes.$inferInsert;

export const quoteItems = mysqlTable(
  "quoteItems",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    quoteId: varchar("quoteId", { length: 36 })
      .notNull()
      .references(() => quotes.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    descricao: varchar("descricao", { length: 255 }).notNull(),
    material: varchar("material", { length: 120 }),
    larguraCm: decimal("larguraCm", { precision: 8, scale: 2 }).notNull(),
    alturaCm: decimal("alturaCm", { precision: 8, scale: 2 }).notNull(),
    quantidade: decimal("quantidade", { precision: 12, scale: 3 })
      .notNull()
      .default("1"),
    /** largura * altura * quantidade / 10000 (server-computed). */
    areaM2: decimal("areaM2", { precision: 12, scale: 4 }).notNull(),
    precoPorM2: decimal("precoPorM2", { precision: 12, scale: 2 }).notNull(),
    acabamento: varchar("acabamento", { length: 120 }),
    valorTotal: decimal("valorTotal", { precision: 12, scale: 2 }).notNull(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    quoteIdIdx: index("idx_quoteItems_quoteId").on(t.quoteId),
    companyIdIdx: index("idx_quoteItems_companyId").on(t.companyId),
  }),
);

export type QuoteItem = typeof quoteItems.$inferSelect;
export type InsertQuoteItem = typeof quoteItems.$inferInsert;

export const artworks = mysqlTable(
  "artworks",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    opId: varchar("opId", { length: 36 }).references(() => ops.id, {
      onDelete: "cascade",
    }),
    quoteId: varchar("quoteId", { length: 36 }).references(() => quotes.id, {
      onDelete: "set null",
    }),
    titulo: varchar("titulo", { length: 255 }).notNull(),
    descricao: text("descricao"),
    fileKey: varchar("fileKey", { length: 255 }).notNull(),
    mimeType: varchar("mimeType", { length: 64 }).notNull(),
    fileSizeBytes: int("fileSizeBytes").notNull(),
    status: mysqlEnum("status", ["pendente", "aprovado", "rejeitado"])
      .notNull()
      .default("pendente"),
    publicToken: varchar("publicToken", { length: 64 }).notNull().unique(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_artworks_userId").on(t.userId),
    opIdIdx: index("idx_artworks_opId").on(t.opId),
    companyIdIdx: index("idx_artworks_companyId").on(t.companyId),
  }),
);

export type Artwork = typeof artworks.$inferSelect;
export type InsertArtwork = typeof artworks.$inferInsert;

export const artworkApprovals = mysqlTable(
  "artworkApprovals",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    artworkId: varchar("artworkId", { length: 36 })
      .notNull()
      .references(() => artworks.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    decisao: mysqlEnum("decisao", ["aprovado", "rejeitado"]).notNull(),
    comentario: text("comentario"),
    aprovadorNome: varchar("aprovadorNome", { length: 255 }),
    aprovadorEmail: varchar("aprovadorEmail", { length: 320 }),
    ipAddress: varchar("ipAddress", { length: 64 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    artworkIdIdx: index("idx_artworkApprovals_artworkId").on(t.artworkId),
    companyIdIdx: index("idx_artworkApprovals_companyId").on(t.companyId),
  }),
);

export type ArtworkApproval = typeof artworkApprovals.$inferSelect;
export type InsertArtworkApproval = typeof artworkApprovals.$inferInsert;

/* ──────────────────────────────────────────────────────────────────────────
 * F2-04 / F2-05 / F2-06 — Mecânica (MEC) vertical
 *
 * Tables appended at the bottom per the parallel-agents schema isolation
 * convention. Existing tables above must NOT be touched.
 *
 * - vehicles: customer-owned vehicles (placa, chassi, marca/modelo/ano…)
 * - serviceOrders: full OS workflow with 9-stage status pipeline
 * - serviceOrderItems: peças + serviços inside an OS
 * - serviceOrderPhotos: fotos de entrada/durante/saida (S3 keys)
 * - serviceOrderPublicTokens: shareable approval links
 * ────────────────────────────────────────────────────────────────────── */

export const vehicles = mysqlTable(
  "vehicles",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    customerId: varchar("customerId", { length: 36 })
      .notNull()
      .references(() => customers.id, { onDelete: "restrict" }),
    placa: varchar("placa", { length: 8 }).notNull(),
    chassi: varchar("chassi", { length: 17 }),
    marca: varchar("marca", { length: 64 }).notNull(),
    modelo: varchar("modelo", { length: 120 }).notNull(),
    ano: int("ano"),
    cor: varchar("cor", { length: 32 }),
    kmAtual: int("kmAtual").notNull().default(0),
    observacoes: text("observacoes"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_vehicles_userId").on(t.userId),
    customerIdIdx: index("idx_vehicles_customerId").on(t.customerId),
    placaIdx: index("idx_vehicles_placa").on(t.placa),
    companyIdIdx: index("idx_vehicles_companyId").on(t.companyId),
  }),
);

export type Vehicle = typeof vehicles.$inferSelect;
export type InsertVehicle = typeof vehicles.$inferInsert;

export const serviceOrders = mysqlTable(
  "serviceOrders",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    customerId: varchar("customerId", { length: 36 })
      .notNull()
      .references(() => customers.id, { onDelete: "restrict" }),
    vehicleId: varchar("vehicleId", { length: 36 })
      .notNull()
      .references(() => vehicles.id, { onDelete: "restrict" }),
    numero: int("numero").notNull(),
    queixaCliente: text("queixaCliente"),
    diagnostico: text("diagnostico"),
    kmEntrada: int("kmEntrada"),
    kmSaida: int("kmSaida"),
    status: mysqlEnum("status", [
      "recepcao",
      "diagnostico",
      "orcamento",
      "aguardando_aprovacao",
      "aguardando_pecas",
      "em_execucao",
      "revisao",
      "pronto",
      "entregue",
    ])
      .notNull()
      .default("recepcao"),
    valorPecas: decimal("valorPecas", { precision: 12, scale: 2 })
      .notNull()
      .default("0"),
    valorMaoObra: decimal("valorMaoObra", { precision: 12, scale: 2 })
      .notNull()
      .default("0"),
    valorTotal: decimal("valorTotal", { precision: 12, scale: 2 })
      .notNull()
      .default("0"),
    dataEntrada: varchar("dataEntrada", { length: 32 }).notNull(),
    dataPrevista: varchar("dataPrevista", { length: 32 }),
    dataSaida: varchar("dataSaida", { length: 32 }),
    /** 0/1 boolean — Drizzle MySQL has no native boolean. Nullable while pending. */
    aprovacaoCliente: tinyint("aprovacaoCliente"),
    aprovacaoData: varchar("aprovacaoData", { length: 32 }),
    aprovacaoIp: varchar("aprovacaoIp", { length: 64 }),
    aprovacaoComentario: text("aprovacaoComentario"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_serviceOrders_userId").on(t.userId),
    customerIdIdx: index("idx_serviceOrders_customerId").on(t.customerId),
    vehicleIdIdx: index("idx_serviceOrders_vehicleId").on(t.vehicleId),
    statusIdx: index("idx_serviceOrders_status").on(t.status),
    companyIdIdx: index("idx_serviceOrders_companyId").on(t.companyId),
  }),
);

export type ServiceOrder = typeof serviceOrders.$inferSelect;
export type InsertServiceOrder = typeof serviceOrders.$inferInsert;

export const serviceOrderItems = mysqlTable(
  "serviceOrderItems",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    serviceOrderId: varchar("serviceOrderId", { length: 36 })
      .notNull()
      .references(() => serviceOrders.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    tipo: mysqlEnum("tipo", ["peca", "servico"]).notNull(),
    codigo: varchar("codigo", { length: 64 }),
    descricao: varchar("descricao", { length: 255 }).notNull(),
    quantidade: decimal("quantidade", { precision: 12, scale: 3 })
      .notNull()
      .default("1"),
    valorUnit: decimal("valorUnit", { precision: 12, scale: 2 }).notNull(),
    valorTotal: decimal("valorTotal", { precision: 12, scale: 2 }).notNull(),
    fornecedor: varchar("fornecedor", { length: 255 }),
    tempoEstimadoHoras: decimal("tempoEstimadoHoras", { precision: 6, scale: 2 }),
    mecanicoResponsavel: varchar("mecanicoResponsavel", { length: 255 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    serviceOrderIdIdx: index("idx_serviceOrderItems_serviceOrderId").on(
      t.serviceOrderId,
    ),
    companyIdIdx: index("idx_serviceOrderItems_companyId").on(t.companyId),
  }),
);

export type ServiceOrderItem = typeof serviceOrderItems.$inferSelect;
export type InsertServiceOrderItem = typeof serviceOrderItems.$inferInsert;

export const serviceOrderPhotos = mysqlTable(
  "serviceOrderPhotos",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    serviceOrderId: varchar("serviceOrderId", { length: 36 })
      .notNull()
      .references(() => serviceOrders.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    tipo: mysqlEnum("tipo", ["entrada", "durante", "saida"]).notNull(),
    fileKey: varchar("fileKey", { length: 255 }).notNull(),
    descricao: varchar("descricao", { length: 255 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    serviceOrderIdIdx: index("idx_serviceOrderPhotos_serviceOrderId").on(
      t.serviceOrderId,
    ),
    companyIdIdx: index("idx_serviceOrderPhotos_companyId").on(t.companyId),
  }),
);

export type ServiceOrderPhoto = typeof serviceOrderPhotos.$inferSelect;
export type InsertServiceOrderPhoto = typeof serviceOrderPhotos.$inferInsert;

export const serviceOrderPublicTokens = mysqlTable(
  "serviceOrderPublicTokens",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    serviceOrderId: varchar("serviceOrderId", { length: 36 })
      .notNull()
      .references(() => serviceOrders.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    token: varchar("token", { length: 64 }).notNull().unique(),
    expiresAt: varchar("expiresAt", { length: 32 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    serviceOrderIdIdx: index("idx_serviceOrderPublicTokens_serviceOrderId").on(
      t.serviceOrderId,
    ),
    companyIdIdx: index("idx_serviceOrderPublicTokens_companyId").on(t.companyId),
  }),
);

export type ServiceOrderPublicToken =
  typeof serviceOrderPublicTokens.$inferSelect;
export type InsertServiceOrderPublicToken =
  typeof serviceOrderPublicTokens.$inferInsert;

/**
 * Inventory (F2-07) — stock items independent of `produtos` catalog. Optional
 * link via `produtoId` when the inventory item maps to a sellable product.
 * Quantity changes only through `inventoryMovements` (audit trail + saldo).
 */
export const inventory = mysqlTable(
  "inventory",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    produtoId: varchar("produtoId", { length: 36 }).references(
      () => produtos.id,
      { onDelete: "set null" },
    ),
    codigo: varchar("codigo", { length: 64 }),
    nome: varchar("nome", { length: 255 }).notNull(),
    unidade: varchar("unidade", { length: 16 }).notNull().default("un"),
    quantidade: decimal("quantidade", { precision: 12, scale: 3 })
      .notNull()
      .default("0"),
    estoqueMinimo: decimal("estoqueMinimo", { precision: 12, scale: 3 })
      .notNull()
      .default("0"),
    custoUnit: decimal("custoUnit", { precision: 12, scale: 2 })
      .notNull()
      .default("0"),
    precoVenda: decimal("precoVenda", { precision: 12, scale: 2 }),
    fornecedorPrincipal: varchar("fornecedorPrincipal", { length: 255 }),
    localizacao: varchar("localizacao", { length: 120 }),
    /** 0/1 — soft-delete flag (MySQL has no boolean in Drizzle). */
    ativo: tinyint("ativo").notNull().default(1),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_inventory_userId").on(t.userId),
    produtoIdIdx: index("idx_inventory_produtoId").on(t.produtoId),
    codigoIdx: index("idx_inventory_codigo").on(t.codigo),
    companyIdIdx: index("idx_inventory_companyId").on(t.companyId),
  }),
);

export type Inventory = typeof inventory.$inferSelect;
export type InsertInventory = typeof inventory.$inferInsert;

export const inventoryMovements = mysqlTable(
  "inventoryMovements",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    inventoryId: varchar("inventoryId", { length: 36 })
      .notNull()
      .references(() => inventory.id, { onDelete: "restrict" }),
    tipo: mysqlEnum("tipo", ["entrada", "saida", "ajuste", "perda"]).notNull(),
    /** Always positive; semantics depend on tipo. */
    quantidade: decimal("quantidade", { precision: 12, scale: 3 }).notNull(),
    saldoApos: decimal("saldoApos", { precision: 12, scale: 3 }).notNull(),
    motivo: varchar("motivo", { length: 255 }),
    referenciaTipo: varchar("referenciaTipo", { length: 32 }),
    referenciaId: varchar("referenciaId", { length: 36 }),
    custoUnitMovimento: decimal("custoUnitMovimento", {
      precision: 12,
      scale: 2,
    }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_inventoryMovements_userId").on(t.userId),
    inventoryIdIdx: index("idx_inventoryMovements_inventoryId").on(t.inventoryId),
    referenciaIdIdx: index("idx_inventoryMovements_referenciaId").on(
      t.referenciaId,
    ),
    companyIdIdx: index("idx_inventoryMovements_companyId").on(t.companyId),
  }),
);

export type InventoryMovement = typeof inventoryMovements.$inferSelect;
export type InsertInventoryMovement = typeof inventoryMovements.$inferInsert;

/**
 * WhatsApp message log (F2-08). Outbound messages go through Z-API; inbound
 * (replies) can be persisted via webhook in the future.
 */
export const whatsappMessages = mysqlTable(
  "whatsappMessages",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    customerId: varchar("customerId", { length: 36 }).references(
      () => customers.id,
      { onDelete: "set null" },
    ),
    telefone: varchar("telefone", { length: 32 }).notNull(),
    mensagem: text("mensagem").notNull(),
    tipo: mysqlEnum("tipo", ["enviada", "recebida", "falhou", "pending"])
      .notNull()
      .default("pending"),
    referenciaTipo: varchar("referenciaTipo", { length: 32 }),
    referenciaId: varchar("referenciaId", { length: 36 }),
    providerMessageId: varchar("providerMessageId", { length: 64 }),
    erro: text("erro"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_whatsappMessages_userId").on(t.userId),
    customerIdIdx: index("idx_whatsappMessages_customerId").on(t.customerId),
    companyIdIdx: index("idx_whatsappMessages_companyId").on(t.companyId),
  }),
);

export type WhatsappMessage = typeof whatsappMessages.$inferSelect;
export type InsertWhatsappMessage = typeof whatsappMessages.$inferInsert;

/* ──────────────────────────────────────────────────────────────────────────
 * F3-01 — Emissão Fiscal (NF-e / NFC-e / NFS-e)
 *
 * Tables appended at the bottom per parallel-agents isolation. Provider is
 * Focus NFe (https://focusnfe.com.br). `companySettings` is the per-user
 * issuer config; `fiscalDocuments` is the log of every emission attempt.
 * ────────────────────────────────────────────────────────────────────── */

export const companySettings = mysqlTable("companySettings", {
  id: varchar("id", { length: 36 }).primaryKey(),
  userId: int("userId")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * F3-08: tenant FK. After migration this becomes the unique key (one
   * settings row per company). Nullable during backfill — see 0010 SQL.
   */
  companyId: varchar("companyId", { length: 36 }).unique(),
  razaoSocial: varchar("razaoSocial", { length: 255 }),
  nomeFantasia: varchar("nomeFantasia", { length: 255 }),
  cnpj: varchar("cnpj", { length: 18 }),
  inscricaoEstadual: varchar("inscricaoEstadual", { length: 32 }),
  inscricaoMunicipal: varchar("inscricaoMunicipal", { length: 32 }),
  regimeTributario: mysqlEnum("regimeTributario", [
    "simples_nacional",
    "lucro_presumido",
    "lucro_real",
  ]).default("simples_nacional"),
  cep: varchar("cep", { length: 9 }),
  endereco: text("endereco"),
  cidade: varchar("cidade", { length: 120 }),
  uf: varchar("uf", { length: 2 }),
  telefone: varchar("telefone", { length: 32 }),
  email: varchar("email", { length: 320 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CompanySettings = typeof companySettings.$inferSelect;
export type InsertCompanySettings = typeof companySettings.$inferInsert;

export const fiscalDocuments = mysqlTable(
  "fiscalDocuments",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    tipo: mysqlEnum("tipo", ["NFe", "NFCe", "NFSe"]).notNull(),
    /** What was billed: pedido | os | quote */
    referenciaTipo: varchar("referenciaTipo", { length: 32 }).notNull(),
    referenciaId: varchar("referenciaId", { length: 36 }).notNull(),
    customerId: varchar("customerId", { length: 36 }).references(
      () => customers.id,
      { onDelete: "set null" },
    ),
    /** Status from provider: rascunho / processando / autorizado / cancelado / rejeitado */
    status: mysqlEnum("status", [
      "rascunho",
      "processando",
      "autorizado",
      "cancelado",
      "rejeitado",
    ])
      .notNull()
      .default("rascunho"),
    /** SEFAZ access key (44 chars NFe / varies for NFSe). */
    chaveAcesso: varchar("chaveAcesso", { length: 64 }),
    numero: varchar("numero", { length: 32 }),
    serie: varchar("serie", { length: 16 }),
    /** Provider-side reference (Focus NFe ref or NFSe rps). */
    providerRef: varchar("providerRef", { length: 64 }).unique(),
    valor: decimal("valor", { precision: 12, scale: 2 }).notNull(),
    pdfKey: varchar("pdfKey", { length: 255 }),
    xmlKey: varchar("xmlKey", { length: 255 }),
    /** Last provider response payload (for debugging). */
    providerResponse: text("providerResponse"),
    /** Provider error message when status=rejeitado. */
    erroMensagem: text("erroMensagem"),
    /** Ambiente: producao | homologacao. */
    ambiente: mysqlEnum("ambiente", ["producao", "homologacao"])
      .notNull()
      .default("homologacao"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_fiscalDocuments_userId").on(t.userId),
    referenciaIdx: index("idx_fiscalDocuments_referencia").on(
      t.referenciaTipo,
      t.referenciaId,
    ),
    customerIdx: index("idx_fiscalDocuments_customerId").on(t.customerId),
    statusIdx: index("idx_fiscalDocuments_status").on(t.status),
    companyIdIdx: index("idx_fiscalDocuments_companyId").on(t.companyId),
  }),
);

export type FiscalDocument = typeof fiscalDocuments.$inferSelect;
export type InsertFiscalDocument = typeof fiscalDocuments.$inferInsert;

/**
 * F3-03 — Asaas payment links.
 *
 * One row per payment link generated through the Asaas gateway. References to
 * pedido / OS / quote are stored as (referenciaTipo, referenciaId) so we don't
 * need a FK per source type. Status mirrors the Asaas lifecycle but uses our
 * pt-BR enum so the UI doesn't depend on provider-specific strings.
 */
export const paymentLinks = mysqlTable(
  "paymentLinks",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    customerId: varchar("customerId", { length: 36 }).references(
      () => customers.id,
      { onDelete: "set null" },
    ),
    /** referenciaTipo: pedido | os | quote */
    referenciaTipo: varchar("referenciaTipo", { length: 32 }).notNull(),
    referenciaId: varchar("referenciaId", { length: 36 }).notNull(),
    valor: decimal("valor", { precision: 12, scale: 2 }).notNull(),
    descricao: varchar("descricao", { length: 255 }),
    /** Método pretendido (cliente pode pagar de outras formas no link Asaas). */
    metodoPreferido: mysqlEnum("metodoPreferido", [
      "pix",
      "boleto",
      "cartao",
      "qualquer",
    ]).default("qualquer"),
    status: mysqlEnum("status", [
      "pendente",
      "pago",
      "vencido",
      "cancelado",
      "estornado",
      "falhou",
    ])
      .default("pendente")
      .notNull(),
    /** Asaas payment id (e.g. "pay_xxx"). */
    providerPaymentId: varchar("providerPaymentId", { length: 64 }).unique(),
    /** URL pública do checkout Asaas. */
    paymentUrl: varchar("paymentUrl", { length: 500 }),
    vencimento: varchar("vencimento", { length: 32 }), // ISO date
    pagoEm: varchar("pagoEm", { length: 32 }), // ISO datetime
    netValue: decimal("netValue", { precision: 12, scale: 2 }),
    providerResponse: text("providerResponse"),
    /**
     * Client-supplied idempotency key (UUID). When set, server dedupes
     * payments.create on (companyId, idempotencyKey) so retries from the
     * offline mutation queue don't double-charge.
     */
    idempotencyKey: varchar("idempotencyKey", { length: 64 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    userIdIdx: index("idx_paymentLinks_userId").on(t.userId),
    customerIdx: index("idx_paymentLinks_customerId").on(t.customerId),
    referenciaIdx: index("idx_paymentLinks_referencia").on(
      t.referenciaTipo,
      t.referenciaId,
    ),
    statusIdx: index("idx_paymentLinks_status").on(t.status),
    companyIdIdx: index("idx_paymentLinks_companyId").on(t.companyId),
    // NULL values don't collide in MySQL unique indexes — legacy rows are safe.
    idempotencyIdx: uniqueIndex("unique_paymentLinks_company_idempotency").on(
      t.companyId,
      t.idempotencyKey,
    ),
  }),
);

export type PaymentLink = typeof paymentLinks.$inferSelect;
export type InsertPaymentLink = typeof paymentLinks.$inferInsert;

/**
 * F3-03 P0 — Webhook idempotency log.
 *
 * Every incoming webhook (Asaas now, others later) gets a row inserted on
 * (provider, eventType, externalId). The unique constraint enforces
 * at-most-once processing — if Asaas retries, the second INSERT throws
 * ER_DUP_ENTRY (1062) and the handler returns 200 OK without re-processing.
 */
export const webhookEvents = mysqlTable(
  "webhookEvents",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    provider: varchar("provider", { length: 32 }).notNull(),
    eventType: varchar("eventType", { length: 64 }).notNull(),
    externalId: varchar("externalId", { length: 128 }).notNull(),
    /** Raw JSON payload kept for forensics. */
    payload: text("payload"),
    processedAt: timestamp("processedAt").defaultNow().notNull(),
  },
  (t) => ({
    uniqIdx: uniqueIndex("uniq_webhookEvents").on(
      t.provider,
      t.eventType,
      t.externalId,
    ),
    providerIdx: index("idx_webhookEvents_provider").on(t.provider),
  }),
);

export type WebhookEvent = typeof webhookEvents.$inferSelect;
export type InsertWebhookEvent = typeof webhookEvents.$inferInsert;

/* ──────────────────────────────────────────────────────────────────────────
 * F3-05 — Portal Web do Cliente
 *
 * Magic-link login (no password) + cookie session for the customer portal.
 * Customers receive a link via WhatsApp/email and enter the portal where
 * they can review all their pedidos/OSs/orcamentos and approve in-line.
 * ────────────────────────────────────────────────────────────────────── */

/**
 * Magic-link tokens for customer portal access (F3-05).
 * Each token is single-use OR has a TTL; customer pode pedir novo.
 */
export const customerMagicLinks = mysqlTable(
  "customerMagicLinks",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill, will be set non-null after migration. */
    companyId: varchar("companyId", { length: 36 }),
    customerId: varchar("customerId", { length: 36 })
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    token: varchar("token", { length: 96 }).notNull().unique(),
    expiresAt: varchar("expiresAt", { length: 32 }).notNull(), // ISO datetime
    usedAt: varchar("usedAt", { length: 32 }), // null = still valid for re-entry until expiresAt
    /** Free-text: where did the link originate (whatsapp, email, manual). */
    origem: varchar("origem", { length: 32 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    customerIdIdx: index("idx_customerMagicLinks_customerId").on(t.customerId),
    expiresAtIdx: index("idx_customerMagicLinks_expiresAt").on(t.expiresAt),
    companyIdIdx: index("idx_customerMagicLinks_companyId").on(t.companyId),
  }),
);
export type CustomerMagicLink = typeof customerMagicLinks.$inferSelect;
export type InsertCustomerMagicLink = typeof customerMagicLinks.$inferInsert;

/**
 * Cookie-based session for the customer portal (separate from auth.users sessions).
 * Stored as HttpOnly cookie set after magic-link validation.
 */
export const customerSessions = mysqlTable(
  "customerSessions",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    customerId: varchar("customerId", { length: 36 })
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    /** F3-08: tenant FK — nullable during backfill. */
    companyId: varchar("companyId", { length: 36 }),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    sessionToken: varchar("sessionToken", { length: 96 }).notNull().unique(),
    expiresAt: varchar("expiresAt", { length: 32 }).notNull(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    sessionTokenIdx: index("idx_customerSessions_sessionToken").on(t.sessionToken),
    customerIdIdx: index("idx_customerSessions_customerId").on(t.customerId),
    companyIdIdx: index("idx_customerSessions_companyId").on(t.companyId),
  }),
);
export type CustomerSession = typeof customerSessions.$inferSelect;
export type InsertCustomerSession = typeof customerSessions.$inferInsert;

/* ──────────────────────────────────────────────────────────────────────────
 * F3-08 — Multiempresa
 *
 * A `user` is an auth identity. A `company` is a tenant. One user may own
 * many companies; access is granted via `companyMembers`. Every domain row
 * is tagged with a `companyId` for isolation (queries filter by companyId,
 * NOT by userId). `userId` columns are kept as creator/audit fields.
 * ────────────────────────────────────────────────────────────────────── */

export const companies = mysqlTable(
  "companies",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    ownerUserId: int("ownerUserId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    nome: varchar("nome", { length: 255 }).notNull(),
    /** Vertical default: cv | mecanica | outro */
    vertical: mysqlEnum("vertical", ["cv", "mecanica", "outro"])
      .default("outro")
      .notNull(),
    ativa: tinyint("ativa").notNull().default(1),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (t) => ({
    ownerIdx: index("idx_companies_ownerUserId").on(t.ownerUserId),
  }),
);
export type Company = typeof companies.$inferSelect;
export type InsertCompany = typeof companies.$inferInsert;

export const companyMembers = mysqlTable(
  "companyMembers",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    companyId: varchar("companyId", { length: 36 })
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    userId: int("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: mysqlEnum("role", ["owner", "admin", "member"])
      .notNull()
      .default("member"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (t) => ({
    companyIdx: index("idx_companyMembers_companyId").on(t.companyId),
    userIdx: index("idx_companyMembers_userId").on(t.userId),
  }),
);
export type CompanyMember = typeof companyMembers.$inferSelect;
