// funcoes-perms.jsx — Catálogo real de permissões (espelho do /roles do main: 53 grupos).
// Normaliza o checkbox-soup legado em 5 formas de controle:
//   escopo (colapsa "ver todos X" + "ver próprio X")  ·  crud (ver/criar/editar/excluir numa linha)
//   sw (toggle avulso)  ·  sel (colapsa N checkboxes mutuamente exclusivos)  ·  raw (chave sem tradução no main)
// `legacyN` = quantas permissões legadas o controle representa. `risco` = ação destrutiva/financeira.
// Expõe window.FUNCOES_PERMS.
(() => {

const G = {
  // ── Balcão e vendas ──
  pos: { label:"PDV (caixa)", legacy:"POS", itens:[
    { k:"pos.venda", t:"crud", label:"Venda de PDV", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"pos.historico", t:"sw", label:"Ver histórico e linha do tempo da venda" },
    { k:"pos.pagamento", t:"sw", label:"Adicionar e editar pagamento" },
    { k:"pos.imprimir", t:"sw", label:"Imprimir fatura" },
    { k:"pos.preco", t:"sw", label:"Editar preço do produto na tela do PDV", risco:true },
    { k:"pos.desc_item", t:"sw", label:"Editar desconto do produto na tela do PDV", risco:true },
    { sub:"O que o operador pode usar no caixa", nota:"No legado são 9 permissões “Desativar …”. Aqui são liberações — o que está desligado o caixa não vê." },
    { k:"pos.f_checkout", t:"sw", neg:"disable_pay_checkout", label:"Pagamento e finalizar venda" },
    { k:"pos.f_rascunho", t:"sw", neg:"disable_draft", label:"Salvar como rascunho" },
    { k:"pos.f_quickpay", t:"sw", neg:"disable_quick_pay", label:"Pagamento rápido" },
    { k:"pos.f_desconto", t:"sw", neg:"disable_discount", label:"Aplicar desconto", risco:true },
    { k:"pos.f_suspensa", t:"sw", neg:"disable_suspend_sale", label:"Suspender venda" },
    { k:"pos.f_credito", t:"sw", neg:"disable_credit_sale", label:"Venda a crédito (a prazo)", risco:true },
    { k:"pos.f_orcamento", t:"sw", neg:"disable_quotation", label:"Gerar orçamento" },
    { k:"pos.f_cartao", t:"sw", neg:"disable_card", label:"Pagamento em cartão" },
  ]},
  sell: { label:"Vendas", legacy:"Vendas", itens:[
    { k:"sell.escopo", t:"escopo", label:"Enxergar vendas", legacyN:2 },
    { k:"sell.filtro", t:"sel", label:"Limitar a vendas com situação", legacyN:4, max:"none",
      opts:[{v:"none",label:"Sem limite"},{v:"paid",label:"Só pagas"},{v:"due",label:"Só a receber"},{v:"partial",label:"Só parciais"},{v:"overdue",label:"Só em atraso"}] },
    { k:"sell.crud", t:"crud", label:"Venda", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"sell.pgto", t:"crud", label:"Pagamento da venda", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"sell.preco", t:"sw", label:"Editar preço do produto na venda", risco:true },
    { k:"sell.desconto", t:"sw", label:"Criar, editar e excluir desconto", risco:true, legacyN:2 },
    { k:"sell.nfnum", t:"sw", label:"Definir e editar número da fatura", risco:true },
    { k:"sell.tipos", t:"sw", label:"Acessar tipos de serviço" },
    { k:"sell.agente", t:"sw", label:"Comissionado vê as vendas dele" },
    { k:"sell.rollback", t:"sw", label:"Reverter a própria venda", risco:true },
  ]},
  draft: { label:"Rascunhos", legacy:"Rascunho", itens:[
    { k:"draft.escopo", t:"escopo", label:"Enxergar rascunhos", legacyN:2 },
    { k:"draft.crud", t:"crud", label:"Rascunho", acoes:["editar","excluir"], legacyN:2 },
  ]},
  quote: { label:"Orçamentos", legacy:"Cotação", itens:[
    { k:"quote.escopo", t:"escopo", label:"Enxergar orçamentos", legacyN:2 },
    { k:"quote.crud", t:"crud", label:"Orçamento", acoes:["editar","excluir"], legacyN:2 },
  ]},
  ship: { label:"Remessas", legacy:"Remessas", itens:[
    { k:"ship.escopo", t:"escopo", label:"Enxergar remessas", legacyN:2 },
    { k:"ship.pendentes", t:"sw", label:"Só remessas pendentes" },
    { k:"ship.agente", t:"sw", label:"Comissionado acessa as remessas dele" },
  ]},
  caixa: { label:"Caixa registradora", legacy:"Caixa registradora", itens:[
    { k:"caixa.ver", t:"sw", label:"Ver caixa registradora" },
    { k:"caixa.fechar", t:"sw", label:"Fechar caixa", risco:true },
  ]},
  precos: { label:"Grupos de preço", legacy:"Acesso a preços de venda", radio:true, itens:[
    { k:"preco.grupo", t:"sel", label:"Grupo de preço que este papel usa", legacyN:2, max:"atacado",
      opts:[{v:"padrao",label:"Preço padrão"},{v:"atacado",label:"ATACADO"}] },
  ]},

  // ── Clientes e fornecedores ──
  cliente: { label:"Clientes", legacy:"Cliente", itens:[
    { k:"cli.escopo", t:"escopo", label:"Enxergar clientes", legacyN:2 },
    { k:"cli.inativos", t:"sel", label:"Clientes sem venda visíveis", legacyN:5, max:"all",
      opts:[{v:"all",label:"Todos, com ou sem venda"},{v:"1m",label:"Sem venda há 1 mês"},{v:"3m",label:"Sem venda há 3 meses"},{v:"6m",label:"Sem venda há 6 meses"},{v:"12m",label:"Sem venda há 1 ano"}] },
    { k:"cli.crud", t:"crud", label:"Cliente", acoes:["criar","editar","excluir"], legacyN:3 },
  ]},
  fornecedor: { label:"Fornecedores", legacy:"Fornecedor", itens:[
    { k:"forn.escopo", t:"escopo", label:"Enxergar fornecedores", legacyN:2 },
    { k:"forn.crud", t:"crud", label:"Fornecedor", acoes:["criar","editar","excluir"], legacyN:3 },
  ]},
  crm: { label:"CRM", legacy:"Crm", itens:[
    { k:"crm.follow", t:"escopo", label:"Enxergar acompanhamentos", legacyN:2 },
    { k:"crm.leads", t:"escopo", label:"Enxergar leads", legacyN:2 },
    { k:"crm.camp", t:"escopo", label:"Enxergar campanhas", legacyN:2 },
    { k:"crm.camp_del", t:"sw", label:"Excluir campanha de outro usuário", risco:true },
    { k:"crm.prop_tpl", t:"sw", label:"Criar e editar modelos de proposta" },
    { k:"crm.prop", t:"sw", label:"Acessar propostas" },
    { k:"crm.rel", t:"sw", label:"Ver relatórios do CRM" },
    { k:"crm.login", t:"sw", label:"Acessar login do contato", risco:true },
    { k:"crm.fontes", t:"sw", label:"Fontes e estágio de vida", legacyN:2 },
  ]},

  // ── Produtos e estoque ──
  produto: { label:"Produtos", legacy:"Produto", itens:[
    { k:"prod.crud", t:"crud", label:"Produto", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"prod.abertura", t:"sw", label:"Lançar estoque de abertura" },
    { k:"prod.custo_ver", t:"sw", label:"Ver preço de compra (custo)", risco:true },
    { k:"prod.custo_edit", t:"sw", label:"Editar preço de compra (custo)", risco:true },
  ]},
  compras: { label:"Compras e ajuste de estoque", legacy:"Ajuste de compra e estoque", itens:[
    { k:"cmp.escopo", t:"escopo", label:"Enxergar compras e ajustes", legacyN:2 },
    { k:"cmp.crud", t:"crud", label:"Compra e ajuste", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"cmp.pgto", t:"crud", label:"Pagamento de compra", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"cmp.status", t:"sw", label:"Atualizar situação da compra" },
  ]},
  cadastros: { label:"Cadastros auxiliares", legacy:"Marca · Unit · Categoría · Taxa de imposto", itens:[
    { k:"cad.marca", t:"crud", label:"Marca", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"cad.unidade", t:"crud", label:"Unidade", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"cad.categoria", t:"crud", label:"Categoria", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"cad.imposto", t:"crud", label:"Taxa de imposto", acoes:["ver","criar","editar","excluir"], legacyN:4 },
  ]},
  manufatura: { label:"Manufatura", legacy:"Manufacturing", itens:[
    { k:"mfg.receita", t:"crud", label:"Receita (ficha técnica)", acoes:["ver","criar","editar"], legacyN:3 },
    { k:"mfg.prod", t:"sw", label:"Acessar produção" },
  ]},

  // ── Produção ──
  cv: { label:"Comunicação Visual", legacy:"ComunicacaoVisual", itens:[
    { k:"cv.orc", t:"crud", label:"Orçamento de CV", acoes:["ver","criar"], legacyN:2 },
    { k:"cv.materiais", t:"sw", label:"Gerenciar materiais" },
    { k:"cv.os_ver", t:"sw", label:"Ver ordens de serviço" },
    { k:"cv.os_status", t:"sw", label:"Atualizar situação da OS" },
    { k:"cv.apont", t:"sw", label:"Registrar apontamentos" },
  ]},
  oficina: { label:"Oficina Auto", legacy:"OficinaAuto", itens:[
    { k:"of.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"of.veiculo", t:"crud", label:"Veículo", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"of.os", t:"crud", label:"Ordem de serviço", acoes:["ver","criar","editar","excluir"], legacyN:4 },
  ]},
  repair: { label:"Repair", legacy:"Repair", itens:[
    { k:"rp.fat_escopo", t:"escopo", label:"Enxergar faturas", legacyN:2 },
    { k:"rp.fat", t:"crud", label:"Fatura", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"rp.fat_status", t:"sw", label:"Alterar situação da fatura" },
    { k:"rp.ws_escopo", t:"escopo", label:"Enxergar folhas de trabalho", legacyN:3, opts3:"atribuídas" },
    { k:"rp.ws", t:"crud", label:"Folha de trabalho", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"rp.ws_status", t:"sw", label:"Criar, editar e excluir situações da folha", legacyN:1 },
  ]},
  consultaos: { label:"Consulta OS", legacy:"ConsultaOs", itens:[
    { k:"cos.atalhos", t:"sw", label:"Acessar atalhos no admin" },
  ]},
  vestuario: { label:"Vestuário", legacy:"Vestuario", itens:[
    { k:"vt.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"vt.tag_ver", t:"sw", label:"Ver etiquetas TAG" },
    { k:"vt.tag_gerar", t:"sw", label:"Gerar etiquetas TAG em lote" },
  ]},

  // ── Financeiro e fiscal ──
  financeiro: { label:"Financeiro", legacy:"Financeiro", itens:[
    { k:"fin.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"fin.dash", t:"sw", label:"Ver dashboard unificado" },
    { sub:"Contas a receber" },
    { k:"fin.ar_ver", t:"sw", label:"Ver contas a receber" },
    { k:"fin.ar_criar", t:"sw", label:"Criar contas a receber" },
    { k:"fin.ar_baixa", t:"sw", label:"Baixar contas a receber", risco:true },
    { sub:"Contas a pagar" },
    { k:"fin.ap_ver", t:"sw", label:"Ver contas a pagar" },
    { k:"fin.ap_criar", t:"sw", label:"Criar contas a pagar" },
    { k:"fin.ap_pagar", t:"sw", label:"Pagar contas a pagar", risco:true },
    { k:"fin.aprovar", t:"sw", label:"Aprovar e rejeitar títulos pendentes", risco:true },
    { sub:"Caixa, bancos e relatórios" },
    { k:"fin.caixa_lanc", t:"sw", label:"Criar lançamentos no caixa", risco:true },
    { k:"fin.caixa_ver", t:"sw", label:"Ver caixa e fluxo" },
    { k:"fin.bancos", t:"sw", label:"Gerenciar contas bancárias", risco:true },
    { k:"fin.concil", t:"sw", label:"Conciliação bancária" },
    { k:"fin.extrato_api", t:"sw", label:"Ver extrato bancário sincronizado da API" },
    { k:"fin.rel", t:"sw", label:"Ver relatórios" },
    { k:"fin.rel_share", t:"sw", label:"Compartilhar relatório por link público", risco:true },
    { k:"fin.contador", t:"sw", label:"Conceder acesso ao contador parceiro (Portal Advisor)", risco:true },
  ]},
  contas: { label:"Contas e despesas", legacy:"Conta · Despesas", itens:[
    { k:"acc.acesso", t:"sw", label:"Acessar contas" },
    { k:"acc.tx", t:"crud", label:"Transação da conta", acoes:["editar","excluir"], legacyN:2 },
    { k:"exp.escopo", t:"escopo", label:"Enxergar despesas", legacyN:2 },
    { k:"exp.crud", t:"crud", label:"Despesa", acoes:["criar","editar","excluir"], legacyN:3 },
  ]},
  nfe: { label:"NF-e Brasil", legacy:"NfeBrasil", itens:[
    { k:"nfe.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"nfe.emitir", t:"sw", label:"Emitir notas fiscais", risco:true },
    { k:"nfe.consultar", t:"sw", label:"Consultar notas emitidas" },
    { k:"nfe.sped", t:"sw", label:"Gerar e exportar SPED" },
    { k:"nfe.config", t:"sw", label:"Gerenciar configurações fiscais", risco:true },
    { k:"nfe.cert", t:"sw", label:"Configurar certificado A1", risco:true },
    { k:"nfe.trib", t:"sw", label:"Gerenciar tributação (regras NCM e padrão)", risco:true },
    { k:"nfe.receb_ver", t:"sw", label:"Ver NF-e recebidas (manifestação)" },
    { k:"nfe.receb_man", t:"sw", label:"Manifestar NF-e recebidas", risco:true },
  ]},
  nfse: { label:"NFS-e", legacy:"NFSe", itens:[
    { k:"nfse.ver", t:"sw", label:"Visualizar notas" },
    { k:"nfse.emitir", t:"sw", label:"Emitir nota de serviço", risco:true },
    { k:"nfse.cancelar", t:"sw", label:"Cancelar nota", risco:true },
    { k:"nfse.config", t:"sw", label:"Gerenciar configurações fiscais", risco:true },
  ]},
  fiscal: { label:"Fiscal", legacy:"Fiscal", raw:true, itens:[
    { k:"fiscal::fiscal.permissao_acesso", t:"raw" },
    { k:"fiscal::fiscal.permissao_nfe_view", t:"raw" },
    { k:"fiscal::fiscal.permissao_nfe_acoes", t:"raw" },
    { k:"fiscal::fiscal.permissao_nfse_view", t:"raw" },
    { k:"fiscal::fiscal.permissao_dfe_manage", t:"raw" },
    { k:"fiscal::fiscal.permissao_sped_export", t:"raw" },
    { k:"fiscal::fiscal.permissao_config_edit", t:"raw" },
  ]},
  pgw: { label:"Payment Gateway", legacy:"PaymentGateway", raw:true, itens:[
    { k:"paymentgateway::paymentgateway.permissao_acesso", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_credenciais_viewAny", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_credenciais_create", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_credenciais_update", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_credenciais_delete", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_cobranca_viewAny", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_cobranca_emit", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_cobranca_cancel", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_cobranca_refund", t:"raw" },
    { k:"paymentgateway::paymentgateway.permissao_webhook_replay", t:"raw" },
  ]},
  rb: { label:"Assinaturas (cobrança recorrente)", legacy:"RecurringBilling", raw:true, itens:[
    { k:"recurringbilling::recurringbilling.permissao_acesso", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_subscriptions_manage", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_subscriptions_cancel", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_plans_manage", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_invoices_view", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_invoices_charge", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_invoices_cancel", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_notes_write", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_favorites_write", t:"raw" },
    { k:"recurringbilling::recurringbilling.permissao_configuracoes_manage", t:"raw" },
  ]},

  // ── RH e ponto ──
  ponto: { label:"Ponto", legacy:"Ponto", itens:[
    { k:"pt.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"pt.colab", t:"sw", label:"Gerenciar colaboradores" },
    { k:"pt.interc", t:"sw", label:"Aprovar intercorrências", risco:true },
    { k:"pt.rel", t:"sw", label:"Visualizar relatórios" },
    { k:"pt.config", t:"sw", label:"Gerenciar configurações", risco:true },
    { k:"pt.afd", t:"sw", label:"Importar AFD, AFDT e CSV", risco:true },
  ]},
  essentials: { label:"RH (licenças, presença, folha)", legacy:"Essentials", itens:[
    { k:"es.tipolic", t:"crud", label:"Tipo de licença", acoes:["ver","criar","editar","excluir"], legacyN:1 },
    { k:"es.lic_escopo", t:"escopo", label:"Enxergar licenças", legacyN:2 },
    { k:"es.lic_aprovar", t:"sw", label:"Aprovar licença", risco:true },
    { k:"es.presenca_escopo", t:"escopo", label:"Enxergar presença", legacyN:2 },
    { k:"es.presenca_web", t:"sw", label:"Registrar a própria presença pela web" },
    { k:"es.presenca_api", t:"sw", label:"Registrar a própria presença pela API" },
    { k:"es.folha", t:"crud", label:"Folha de pagamento", acoes:["ver","criar","editar","excluir"], legacyN:4, risco:true },
    { k:"es.compgto", t:"crud", label:"Componente de pagamento", acoes:["ver","criar"], legacyN:2 },
    { k:"es.depto", t:"crud", label:"Departamento e designação", acoes:["ver","criar","editar","excluir"], legacyN:2 },
    { k:"es.tarefas", t:"sw", label:"Atribuir tarefas a outras pessoas" },
    { k:"es.todo", t:"crud", label:"Tarefas (to-do)", acoes:["criar","editar","excluir"], legacyN:3 },
    { k:"es.msg", t:"crud", label:"Mensagens", acoes:["ver","criar"], legacyN:2 },
    { k:"es.metas", t:"sw", label:"Acessar metas de venda" },
  ]},

  // ── Relatórios ──
  relatorio: { label:"Relatórios", legacy:"Relatório", itens:[
    { k:"rel.compra_venda", t:"sw", label:"Compra e venda" },
    { k:"rel.fiscal", t:"sw", label:"Fiscal" },
    { k:"rel.forn_cli", t:"sw", label:"Fornecedor e cliente" },
    { k:"rel.despesa", t:"sw", label:"Despesas" },
    { k:"rel.lucro", t:"sw", label:"Lucros e perdas", risco:true },
    { k:"rel.estoque", t:"sw", label:"Estoque, ajuste e vencimento", legacyN:1 },
    { k:"rel.estoque_local", t:"sw", label:"Estoque de um produto por local (somente leitura)" },
    { k:"rel.tendencia", t:"sw", label:"Tendência de produto" },
    { k:"rel.log", t:"sw", label:"Log" },
    { k:"rel.agente", t:"sw", label:"Comissionados" },
    { k:"rel.valor_estoque", t:"sw", label:"Valor do estoque", risco:true },
    { k:"dash.home", t:"sw", label:"Ver dados do painel inicial" },
    { k:"ss.acessar", t:"sw", label:"Acessar planilhas" },
    { k:"ss.criar", t:"sw", label:"Criar planilha" },
  ]},

  // ── Sistema ──
  usuario: { label:"Usuários e papéis", legacy:"Usuário · Papéis", itens:[
    { k:"usr.crud", t:"crud", label:"Usuário", acoes:["ver","criar","editar","excluir"], legacyN:4, risco:true },
    { k:"role.crud", t:"crud", label:"Papel (função)", acoes:["ver","criar","editar","excluir"], legacyN:4, risco:true },
  ]},
  config: { label:"Configurações", legacy:"Configurações · Outras", itens:[
    { k:"cfg.empresa", t:"sw", label:"Configuração da empresa", risco:true },
    { k:"cfg.barras", t:"sw", label:"Configurações de código de barras" },
    { k:"cfg.fatura", t:"sw", label:"Configurações de fatura" },
    { k:"cfg.impressoras", t:"sw", label:"Impressoras" },
    { k:"cfg.notif", t:"sw", label:"Modelos de notificação (ver, editar e enviar)" },
    { k:"cfg.home_cards", t:"sw", label:"Configurar os cartões da tela inicial" },
    { k:"out.resp_venda", t:"sw", label:"Ser responsável pela venda (service staff)", nota_col:"roles.is_service_staff" },
    { k:"out.export", t:"sw", label:"Ver botões de exportação nas tabelas (CSV, Excel, PDF, imprimir)" },
    { k:"res.escopo", t:"escopo", label:"Enxergar reservas", legacyN:2 },
    { k:"arq.anexos", t:"sw", label:"Gerenciar anexos via Admin Center" },
  ]},
  auditoria: { label:"Auditoria", legacy:"Auditoria", itens:[
    { k:"aud.ver", t:"sw", label:"Ver histórico de alterações" },
    { k:"aud.rev", t:"sel", label:"Reverter ações", legacyN:3, max:"all",
      opts:[{v:"none",label:"Não pode reverter"},{v:"own24",label:"Só as próprias, até 24 h"},{v:"any30",label:"Qualquer ação, até 30 dias"},{v:"all",label:"Sem limite (superadmin)"}], risco:true },
  ]},
  patrimonio: { label:"Patrimônio", legacy:"AssetManagement", itens:[
    { k:"as.crud", t:"crud", label:"Recurso (ativo)", acoes:["ver","criar","editar","excluir"], legacyN:4 },
    { k:"as.manut", t:"escopo", label:"Enxergar manutenções", legacyN:2 },
  ]},
  kb: { label:"Base de conhecimento", legacy:"KB", itens:[
    { k:"kb.ver", t:"sw", label:"Ver biblioteca" },
    { k:"kb.hist", t:"sw", label:"Ver histórico de versões" },
    { k:"kb.del", t:"sw", label:"Soft-delete LGPD", risco:true },
    { k:"kb.restore", t:"sw", label:"Restaurar documento excluído", risco:true },
  ]},
  gov: { label:"Governança", legacy:"Governance", itens:[
    { k:"gv.painel", t:"sw", label:"Ver painel de governança" },
    { k:"gv.policies", t:"sw", label:"Editar policies (mcp_governance_rules)", risco:true },
    { k:"gv.audit", t:"sw", label:"Ver audit log" },
  ]},
  jana: { label:"Copiloto Jana e MCP", legacy:"Jana", itens:[
    { sub:"Copiloto" },
    { k:"ja.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"ja.chat", t:"sw", label:"Conversar (chat IA)" },
    { k:"ja.metas", t:"sw", label:"Gerenciar metas" },
    { k:"ja.metas_plat", t:"sw", label:"Configurar metas da plataforma (superadmin)", risco:true },
    { k:"ja.custos", t:"sw", label:"Visualizar custos de IA (admin)" },
    { sub:"MCP — leitura" },
    { k:"mcp.server", t:"sw", label:"Acessar o MCP server" },
    { k:"mcp.tarefas_ler", t:"sw", label:"Ler tarefas e cycle ativo" },
    { k:"mcp.adr", t:"sw", label:"Ler ADRs (decisões arquiteturais)" },
    { k:"mcp.logs", t:"sw", label:"Ler session logs" },
    { k:"mcp.ctx_fin", t:"sw", label:"Acessar contexto financeiro", risco:true },
    { k:"mcp.ctx_tec", t:"sw", label:"Acessar contexto técnico" },
    { sub:"MCP — escrita" },
    { k:"mcp.tarefas_esc", t:"sw", label:"Criar, atualizar e comentar tarefas" },
    { k:"mcp.tarefas_avanca", t:"sw", label:"Avançar tarefas (mutação não-terminal)" },
    { k:"mcp.tarefas_fecha", t:"sw", label:"Fechar tarefas (done ou cancelled)", risco:true },
    { k:"mcp.cycles", t:"sw", label:"Gerenciar cycles e goals" },
    { k:"mcp.projetos", t:"sw", label:"Gerenciar projetos, epics e componentes" },
    { k:"mcp.kb", t:"sw", label:"Gerenciar KB MCP (mcp_memory_documents)" },
    { sub:"MCP — sessões Claude Code" },
    { k:"mcp.sess_escopo", t:"escopo", label:"Enxergar sessões Claude Code", legacyN:3 },
    { k:"mcp.sess_gov", t:"sw", label:"Ver todas as sessões e governança", risco:true },
    { k:"mcp.sess_curar", t:"sw", label:"Curar sessões" },
    { k:"mcp.sess_ingerir", t:"sw", label:"Ingerir as próprias sessões" },
    { k:"mcp.uso_escopo", t:"escopo", label:"Enxergar uso e custo do Claude Code", legacyN:2 },
    { sub:"MCP — handoff de design" },
    { k:"mcp.ho_ack", t:"sw", label:"Fechar handoff (handoff-ack)" },
    { k:"mcp.ho_submit", t:"sw", label:"Submeter handoff assinado (handoff-submit)" },
    { k:"mcp.ho_lever", t:"sw", label:"Rotear estado de handoff na fila", risco:true },
  ]},
  whats: { label:"WhatsApp", legacy:"Whatsapp", itens:[
    { k:"wa.acesso", t:"sw", label:"Acessar o módulo" },
    { k:"wa.enviar", t:"sw", label:"Enviar mensagem manual" },
    { k:"wa.atribuir", t:"sw", label:"Atribuir conversa a atendente" },
    { k:"wa.tpl", t:"sw", label:"Gerenciar templates HSM e locais" },
    { k:"wa.drivers", t:"sw", label:"Configurar drivers (Z-API e Meta)", risco:true },
    { k:"wa.metricas", t:"sw", label:"Ver métricas (custo e deflection)" },
    { k:"wa.todos", t:"sw", label:"Ver conversas de todos os números", risco:true },
  ]},
  oi: { label:"Office Impresso (licenças Delphi)", legacy:"Officeimpresso", itens:[
    { k:"oi.modulo", t:"sw", label:"Acessar o módulo" },
    { k:"oi.maquinas", t:"sw", label:"Liberar e bloquear máquinas (suporte)", risco:true },
    { k:"oi.empresa", t:"sw", label:"Bloquear empresa inteira e exigir versão", risco:true },
    { k:"oi.lic_del", t:"sw", label:"Excluir licença (destrutivo)", risco:true },
    { k:"oi.clientes", t:"sw", label:"Liberar clientes (credenciais Delphi)", risco:true },
  ]},
  integr: { label:"Integrações", legacy:"Woocommerce · Connector · Cms · ProductCatalogue · Superadmin", itens:[
    { k:"woo.cat", t:"sw", label:"Sincronizar categorias de produto" },
    { k:"woo.prod", t:"sw", label:"Sincronizar produtos" },
    { k:"woo.ped", t:"sw", label:"Sincronizar pedidos" },
    { k:"woo.tax", t:"sw", label:"Mapear taxas de imposto" },
    { k:"woo.api", t:"sw", label:"Acessar configurações da API WooCommerce", risco:true },
    { k:"conn.modulo", t:"sw", label:"Módulo Connector (API e webhooks)", risco:true },
    { k:"cms.modulo", t:"sw", label:"Módulo CMS" },
    { k:"pcat.modulo", t:"sw", label:"Módulo Catálogo de produtos" },
    { k:"sa.pacotes", t:"sw", label:"Acessar assinaturas de pacotes", risco:true },
  ]},
};

const DOMINIOS = [
  { id:"balcao",  label:"Balcão e vendas",       grupos:["pos","sell","draft","quote","ship","caixa","precos"] },
  { id:"pessoas", label:"Clientes e fornecedores", grupos:["cliente","fornecedor","crm"] },
  { id:"estoque", label:"Produtos e estoque",     grupos:["produto","compras","cadastros","manufatura"] },
  { id:"producao",label:"Produção",               grupos:["cv","oficina","repair","consultaos","vestuario"] },
  { id:"dinheiro",label:"Financeiro e fiscal",    grupos:["financeiro","contas","nfe","nfse","fiscal","pgw","rb"] },
  { id:"rh",      label:"RH e ponto",             grupos:["ponto","essentials"] },
  { id:"analise", label:"Relatórios e painel",    grupos:["relatorio"] },
  { id:"sistema", label:"Sistema",                grupos:["usuario","config","auditoria","patrimonio","kb","gov","jana","whats","oi","integr"] },
];

const ESCOPO_OPTS = [{ v:"all", label:"Todos" }, { v:"own", label:"Só os próprios" }, { v:"none", label:"Sem acesso" }];

// Presets = ponto de partida das funções padrão (o que o legado chama de "papel").
const PRESETS = {
  atendente: {
    "pos.venda":["ver","criar"], "pos.historico":true, "pos.pagamento":true, "pos.imprimir":true,
    "pos.f_checkout":true, "pos.f_rascunho":true, "pos.f_quickpay":true, "pos.f_suspensa":true, "pos.f_orcamento":true, "pos.f_cartao":true,
    "sell.escopo":"all", "sell.filtro":"none", "sell.crud":["criar"], "sell.tipos":true,
    "draft.escopo":"own", "draft.crud":["editar"], "quote.escopo":"all", "quote.crud":["editar"],
    "ship.escopo":"all", "caixa.ver":true, "preco.grupo":"padrao",
    "cli.escopo":"all", "cli.inativos":"all", "cli.crud":["criar","editar"],
    "prod.crud":["ver"], "cv.orc":["ver","criar"], "cv.os_ver":true, "cv.os_status":true,
    "out.resp_venda":true, "dash.home":true, "ja.chat":true, "ja.acesso":true,
    "wa.acesso":true, "wa.enviar":true, "wa.atribuir":true,
  },
  producao: {
    "prod.crud":["ver"], "cmp.escopo":"all", "cmp.crud":["editar"], "cmp.status":true,
    "cv.os_ver":true, "cv.os_status":true, "cv.apont":true, "cv.materiais":true,
    "of.acesso":true, "of.veiculo":["ver"], "of.os":["ver","editar"],
    "rp.ws_escopo":"own", "rp.ws":["editar"], "rp.ws_status":true,
    "mfg.receita":["ver"], "mfg.prod":true, "cli.escopo":"all", "cli.inativos":"all", "dash.home":true,
    "rel.estoque":true, "rel.estoque_local":true,
  },
  financeiro: {
    "sell.escopo":"all", "sell.filtro":"none", "cli.escopo":"all", "cli.inativos":"all",
    "fin.acesso":true, "fin.dash":true, "fin.ar_ver":true, "fin.ar_criar":true, "fin.ar_baixa":true,
    "fin.ap_ver":true, "fin.ap_criar":true, "fin.ap_pagar":true, "fin.caixa_ver":true, "fin.concil":true,
    "fin.extrato_api":true, "fin.rel":true, "fin.bancos":true,
    "acc.acesso":true, "exp.escopo":"all", "exp.crud":["criar","editar"],
    "nfe.acesso":true, "nfe.emitir":true, "nfe.consultar":true, "nfe.sped":true, "nfe.receb_ver":true,
    "nfse.ver":true, "nfse.emitir":true,
    "rel.compra_venda":true, "rel.fiscal":true, "rel.forn_cli":true, "rel.despesa":true, "rel.lucro":true,
    "caixa.ver":true, "caixa.fechar":true, "prod.custo_ver":true, "out.export":true, "dash.home":true,
  },
  vendas: {
    "sell.escopo":"own", "sell.filtro":"none", "sell.crud":["criar"], "sell.agente":true,
    "quote.escopo":"own", "quote.crud":["editar"], "draft.escopo":"own",
    "cli.escopo":"own", "cli.inativos":"all", "cli.crud":["criar","editar"],
    "crm.follow":"own", "crm.leads":"own", "crm.camp":"own", "crm.prop":true, "crm.rel":true,
    "prod.crud":["ver"], "preco.grupo":"padrao", "rel.agente":true, "dash.home":true,
    "pos.venda":["ver","criar"], "pos.f_checkout":true, "pos.f_orcamento":true, "pos.f_cartao":true,
  },
  consulta: {
    "sell.escopo":"all", "sell.filtro":"none", "cli.escopo":"all", "cli.inativos":"all", "forn.escopo":"all",
    "prod.crud":["ver"], "cmp.escopo":"all", "fin.acesso":true, "fin.ar_ver":true, "fin.ap_ver":true, "fin.rel":true,
    "nfe.acesso":true, "nfe.consultar":true, "nfse.ver":true, "aud.ver":true,
    "rel.compra_venda":true, "rel.fiscal":true, "rel.forn_cli":true, "rel.despesa":true,
    "out.export":true, "dash.home":true,
  },
};

window.FUNCOES_PERMS = { G, DOMINIOS, ESCOPO_OPTS, PRESETS };
})();
