<?php

namespace Modules\Jana\Services\Skills;

use App\Util\OtelHelper;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Modules\Jana\Entities\Mcp\McpSkill;
use Modules\Jana\Entities\Mcp\McpSkillVersion;
use Symfony\Component\Yaml\Yaml;

/**
 * ADR 0076 — publica version pra git via GitHub API.
 *
 * Fluxo:
 *  1. Gera SKILL.md (frontmatter YAML + body)
 *  2. PUT no GitHub Contents API (cria commit em branch nova)
 *  3. Cria PR via Pulls API
 *  4. Salva pr_number em mcp_skill_versions (anti-loop)
 *
 * GitHub API exige PAT com scope `repo`. Configurar via:
 *   GITHUB_API_TOKEN no .env
 *   COPILOTO_PUBLISH_REPO=wagnerra23/oimpresso.com no .env (ou config)
 */
class PublicarSkillNoGitService
{
    public function publish(McpSkillVersion $version): array
    {
        // D9.a (Wave 18 SATURATION) — span publish skill git PR (operação cara — GitHub API).
        return OtelHelper::span('jana.skill.publish', [
            'skill_id' => $version->skill_id,
            'version' => $version->version,
        ], fn () => $this->publishInternal($version));
    }

    private function publishInternal(McpSkillVersion $version): array
    {
        $skill = $version->skill;
        if (! $skill) {
            throw new \RuntimeException('Version sem skill associada.');
        }

        $token = env('GITHUB_API_TOKEN') ?: config('services.github.token');
        if (empty($token)) {
            throw new \RuntimeException('GITHUB_API_TOKEN não configurado.');
        }

        $repo = env('COPILOTO_PUBLISH_REPO', 'wagnerra23/oimpresso.com');
        $baseBranch = env('COPILOTO_PUBLISH_BASE_BRANCH', 'main');
        $newBranch = "skill/publish-{$skill->slug}-v{$version->version}-".substr(md5(uniqid('', true)), 0, 6);

        $skillMd = $this->generateSkillMd($version);
        $path = $skill->git_path ?: ".claude/skills/{$skill->slug}/SKILL.md";

        if (config('copiloto.dry_run', false)) {
            Log::channel('copiloto-ai')->info('PublicarSkillNoGit DRY_RUN', [
                'skill' => $skill->slug,
                'version' => $version->version,
                'path' => $path,
                'branch' => $newBranch,
                'skillMdChars' => mb_strlen($skillMd),
            ]);

            return [
                'dry_run'   => true,
                'branch'    => $newBranch,
                'path'      => $path,
                'pr_number' => null,
                'pr_url'    => null,
            ];
        }

        // 1. Pega SHA do base branch
        $baseSha = $this->getBranchSha($repo, $baseBranch, $token);

        // 2. Cria branch nova
        $this->createBranch($repo, $newBranch, $baseSha, $token);

        // 3. Pega SHA atual do arquivo (necessário pra UPDATE — se não existe, é CREATE)
        $fileSha = $this->getFileSha($repo, $path, $newBranch, $token);

        // 4. PUT contents — commit no branch novo
        $commitMsg = "skill({$skill->slug}): publish v{$version->version}\n\n"
            ."Origem: UI Skills (mcp_skill_versions.id={$version->id})\n"
            ."Rationale (problema): ".mb_substr((string) $version->rationale_problem, 0, 200)."\n\n"
            ."🤖 Generated by Publish-to-git";

        $putResp = Http::withToken($token)
            ->withHeaders(['Accept' => 'application/vnd.github.v3+json'])
            ->put("https://api.github.com/repos/{$repo}/contents/".rawurlencode($path), array_filter([
                'message' => $commitMsg,
                'content' => base64_encode($skillMd),
                'branch'  => $newBranch,
                'sha'     => $fileSha, // null se CREATE, setado se UPDATE
            ], fn ($v) => $v !== null));

        if (! $putResp->successful()) {
            throw new \RuntimeException("PUT contents falhou ".$putResp->status().": ".$putResp->body());
        }

        // 5. Cria PR
        $prTitle = "skill({$skill->slug}): publish v{$version->version} via UI";
        $prBody = $this->generatePrBody($version);

        $prResp = Http::withToken($token)
            ->withHeaders(['Accept' => 'application/vnd.github.v3+json'])
            ->post("https://api.github.com/repos/{$repo}/pulls", [
                'title' => $prTitle,
                'head'  => $newBranch,
                'base'  => $baseBranch,
                'body'  => $prBody,
            ]);

        if (! $prResp->successful()) {
            throw new \RuntimeException("POST pulls falhou ".$prResp->status().": ".$prResp->body());
        }

        $prData = $prResp->json();
        $prNumber = (int) ($prData['number'] ?? 0);
        $prUrl = (string) ($prData['html_url'] ?? '');

        // 6. Anti-loop: registra pr_number na version ANTES do merge
        $version->update([
            'pr_number'           => $prNumber,
            'published_to_git_at' => now(), // será atualizado quando webhook confirmar merge
        ]);

        return [
            'dry_run'   => false,
            'branch'    => $newBranch,
            'path'      => $path,
            'pr_number' => $prNumber,
            'pr_url'    => $prUrl,
        ];
    }

    private function generateSkillMd(McpSkillVersion $version): string
    {
        $frontmatterYaml = Yaml::dump(
            $version->frontmatter_json ?? [],
            inline: 4,
            indent: 2,
            flags: Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK
        );

        return "---\n".trim($frontmatterYaml)."\n---\n\n".ltrim((string) $version->body_markdown);
    }

    private function generatePrBody(McpSkillVersion $version): string
    {
        $skill = $version->skill;
        $body = "**Skill:** `{$skill->slug}` v{$version->version}\n\n";
        $body .= "**Origem:** UI Skills (`mcp_skill_versions.id={$version->id}`)\n\n";

        if (! empty($version->rationale_problem)) {
            $body .= "## Problema observado\n{$version->rationale_problem}\n\n";
        }
        if (! empty($version->rationale_hypothesis)) {
            $body .= "## Hipótese de fix\n{$version->rationale_hypothesis}\n\n";
        }
        if (! empty($version->rationale_success_metric)) {
            $body .= "## Métrica de sucesso\n{$version->rationale_success_metric}\n\n";
        }
        if (! empty($version->rationale_rollback)) {
            $body .= "## Plano de rollback\n{$version->rationale_rollback}\n\n";
        }

        $body .= "---\n\n🤖 Generated by Publish-to-git (ADR 0076)";

        return $body;
    }

    private function getBranchSha(string $repo, string $branch, string $token): string
    {
        $resp = Http::withToken($token)
            ->withHeaders(['Accept' => 'application/vnd.github.v3+json'])
            ->get("https://api.github.com/repos/{$repo}/git/ref/heads/{$branch}");
        if (! $resp->successful()) {
            throw new \RuntimeException("getBranchSha {$branch} falhou: ".$resp->status());
        }
        return $resp->json('object.sha');
    }

    private function createBranch(string $repo, string $newBranch, string $baseSha, string $token): void
    {
        $resp = Http::withToken($token)
            ->withHeaders(['Accept' => 'application/vnd.github.v3+json'])
            ->post("https://api.github.com/repos/{$repo}/git/refs", [
                'ref' => "refs/heads/{$newBranch}",
                'sha' => $baseSha,
            ]);
        if (! $resp->successful()) {
            throw new \RuntimeException("createBranch falhou: ".$resp->status().": ".$resp->body());
        }
    }

    private function getFileSha(string $repo, string $path, string $branch, string $token): ?string
    {
        $resp = Http::withToken($token)
            ->withHeaders(['Accept' => 'application/vnd.github.v3+json'])
            ->get("https://api.github.com/repos/{$repo}/contents/".rawurlencode($path), [
                'ref' => $branch,
            ]);
        if ($resp->status() === 404) {
            return null; // CREATE
        }
        if (! $resp->successful()) {
            throw new \RuntimeException("getFileSha falhou: ".$resp->status());
        }
        return $resp->json('sha');
    }
}
