<?php

declare(strict_types=1);

namespace Modules\KB\Entities;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Modules\KB\Entities\Concerns\BelongsToBusinessTrait;

/**
 * KbEdge — aresta tipada entre 2 kb_nodes.
 *
 * Contrato: memory/requisitos/KB/SCHEMA-DB-V1.md §4
 *
 * Tipos canônicos de aresta:
 *   - supersedes        (auto)  ← frontmatter `supersedes:` de ADR
 *   - charter-of        (auto)  ← path *.charter.md ao lado de .tsx
 *   - references-data   (auto)  ← regex #OS-1234 etc em body
 *   - cross-link        (auto)  ← #kb-XXX no body_blocks
 *   - ai-related        (auto)  ← cosine similarity ONDA 4
 *   - related-by-tag    (auto)  ← tag overlap + cat/equip bonus
 *   - next-in-path      (manual)← editor de trilha
 *   - fix-of-decision   (manual)← editor de troubleshooter
 *
 * UNIQUE (business_id, from_node_id, to_node_id, edge_type) impede dupe.
 *
 * @property int    $id
 * @property int    $business_id
 * @property int    $from_node_id
 * @property int    $to_node_id
 * @property string $edge_type
 * @property string $weight
 * @property array|null $payload
 * @property string $generated_by
 */
class KbEdge extends Model
{
    use BelongsToBusinessTrait;

    protected $table = 'kb_edges';

    protected $fillable = [
        'business_id', 'from_node_id', 'to_node_id',
        'edge_type', 'weight', 'payload', 'generated_by',
    ];

    protected $casts = [
        'business_id'  => 'integer',
        'from_node_id' => 'integer',
        'to_node_id'   => 'integer',
        'weight'       => 'decimal:3',
        'payload'      => 'array',
    ];

    public const EDGE_TYPES = [
        'supersedes', 'charter-of', 'references-data', 'cross-link',
        'ai-related', 'related-by-tag', 'next-in-path', 'fix-of-decision',
    ];

    public const GENERATED_BY = [
        'manual', 'bridge_job', 'ai_embed', 'tag_overlap', 'user_action',
    ];

    public function fromNode(): BelongsTo
    {
        return $this->belongsTo(KbNode::class, 'from_node_id');
    }

    public function toNode(): BelongsTo
    {
        return $this->belongsTo(KbNode::class, 'to_node_id');
    }

    public function scopeOfType(Builder $q, string $type): Builder
    {
        return $q->where('edge_type', $type);
    }

    public function scopeAutoGenerated(Builder $q): Builder
    {
        return $q->whereIn('generated_by', ['bridge_job', 'ai_embed', 'tag_overlap']);
    }

    public function scopeManual(Builder $q): Builder
    {
        return $q->whereIn('generated_by', ['manual', 'user_action']);
    }
}
