// Mock data — Clientes (Fase 3 piloto)
const CLI_LIST = [
  { id:"1024", name:"Padaria Estrela",        cnpj:"[REDACTED]", contact:"Renato Silva",     phone:"(11) 98765-4321", email:"renato@padariaestrela.com.br", city:"São Paulo",    uf:"SP", segment:"Alimentação", since:"2019-03", lastOrder:"2026-04-22", orders:47, ltv:"R$ [redacted Tier 0]",  status:"ativo",     tags:["fidelidade","prazo-30"] },
  { id:"1025", name:"Mercado União",          cnpj:"[REDACTED]", contact:"Helena Rocha",     phone:"(11) 91234-5678", email:"compras@mercadouniao.com",     city:"Guarulhos",    uf:"SP", segment:"Varejo",       since:"2020-08", lastOrder:"2026-04-26", orders:31, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["recorrente"] },
  { id:"1026", name:"Auto Posto Águia",       cnpj:"[REDACTED]", contact:"Marcos Pinheiro",  phone:"(11) 92345-6789", email:"marcos@autopostoaguia.com.br", city:"Osasco",       uf:"SP", segment:"Combustível",  since:"2018-11", lastOrder:"2026-03-15", orders:19, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["prazo-30"] },
  { id:"1027", name:"Farmácia Vida Plena",    cnpj:"[REDACTED]", contact:"Camila Duarte",    phone:"(11) 93456-7890", email:"camila@vidaplena.com.br",      city:"Santo André",  uf:"SP", segment:"Saúde",        since:"2021-06", lastOrder:"2026-04-28", orders:24, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["fidelidade"] },
  { id:"1028", name:"Construtora Horizonte",  cnpj:"[REDACTED]", contact:"Eduardo Mello",    phone:"(11) 94567-8901", email:"eduardo@horizonte.com.br",     city:"São Paulo",    uf:"SP", segment:"Construção",   since:"2017-02", lastOrder:"2026-01-20", orders:8,  ltv:"R$ [redacted Tier 0]",  status:"inativo",   tags:["alto-ticket"] },
  { id:"1029", name:"Pet Shop Latido Feliz",  cnpj:"[REDACTED]", contact:"Aline Souza",      phone:"(11) 95678-9012", email:"aline@latidofeliz.com.br",     city:"Diadema",      uf:"SP", segment:"Pet",          since:"2022-09", lastOrder:"2026-04-29", orders:12, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["novo"] },
  { id:"1030", name:"Restaurante Sabor da Casa",cnpj:"[REDACTED]",contact:"Júlio Mendes",    phone:"(11) 96789-0123", email:"julio@sabordacasa.com.br",     city:"São Paulo",    uf:"SP", segment:"Alimentação",  since:"2019-11", lastOrder:"2026-04-30", orders:38, ltv:"R$ [redacted Tier 0]",  status:"ativo",     tags:["recorrente","fidelidade"] },
  { id:"1031", name:"Escola Saber Mais",      cnpj:"[REDACTED]", contact:"Paula Andrade",    phone:"(11) 97890-1234", email:"paula@sabermais.edu.br",       city:"São Bernardo", uf:"SP", segment:"Educação",     since:"2020-02", lastOrder:"2026-03-28", orders:14, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["prazo-30"] },
  { id:"1032", name:"Loja do Bairro",         cnpj:"[REDACTED]", contact:"Roberto Lima",     phone:"(11) 98901-2345", email:"roberto@lojadobairro.com.br",  city:"São Paulo",    uf:"SP", segment:"Varejo",       since:"2023-04", lastOrder:"2025-12-15", orders:5,  ltv:"R$ [redacted Tier 0]",    status:"inativo",   tags:["novo"] },
  { id:"1033", name:"Distribuidora Brasil",   cnpj:"[REDACTED]", contact:"Sandra Vieira",    phone:"(11) 99012-3456", email:"sandra@distbrasil.com.br",     city:"Barueri",      uf:"SP", segment:"Distribuição", since:"2016-05", lastOrder:"2026-04-25", orders:62, ltv:"R$ [redacted Tier 0]",  status:"ativo",     tags:["alto-ticket","fidelidade"] },
  { id:"1034", name:"Salão Beleza Pura",      cnpj:"[REDACTED]", contact:"Patrícia Gomes",   phone:"(11) 90123-4567", email:"patricia@belezapura.com.br",   city:"São Paulo",    uf:"SP", segment:"Beleza",       since:"2021-10", lastOrder:"2026-04-18", orders:21, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["recorrente"] },
  { id:"1035", name:"Imobiliária Lar Bom",    cnpj:"[REDACTED]", contact:"Fernando Castro",  phone:"(11) 91234-5670", email:"fernando@larbom.com.br",       city:"Santo André",  uf:"SP", segment:"Imobiliário",  since:"2018-07", lastOrder:"2026-02-10", orders:11, ltv:"R$ [redacted Tier 0]",   status:"ativo",     tags:["prazo-60"] },
];

const CLI_SEGMENTS = [...new Set(CLI_LIST.map(c => c.segment))];

window.CLI_DATA = { CLI_LIST, CLI_SEGMENTS };
