"""
Wrapper MySQL pra escrita idempotente do importer.

3 modos de operação:
  - dry_run: imprime SQL + salva em output/dry-run-<ts>.sql, não executa
  - local:   conecta em oimpresso.test (Herd local Wagner), executa
  - prod:    conecta em Hostinger MySQL via Remote MySQL whitelist (perigoso)

UPSERT idempotente via INSERT ... ON DUPLICATE KEY UPDATE — chave por
(business_id, legacy_source, legacy_id).
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

try:
    import pymysql
    import pymysql.cursors
except ImportError:
    print(
        "⚠️  pymysql não instalado. Rode: pip install pymysql\n"
        "   (necessário só pra modo --target local|prod; --target dry-run funciona sem)",
        file=sys.stderr,
    )
    pymysql = None  # type: ignore


class MysqlWriter:
    """Encapsula escrita MySQL ou geração SQL pra dry-run."""

    def __init__(
        self,
        target: str = "dry-run",
        host: str = "127.0.0.1",
        port: int = 3306,
        user: str = "root",
        password: str = "",
        database: str = "oimpresso",
        output_dir: Path | None = None,
        importer_version: str = "0.1.0",
    ) -> None:
        self.target = target
        self.host = host
        self.port = port
        self.user = user
        self.password = password
        self.database = database
        self.output_dir = output_dir or Path("output")
        self.importer_version = importer_version

        self.con = None
        self.dry_run_lines: list[str] = []
        self.stats = {"inserts": 0, "updates": 0, "errors": 0}

        self.dry_run_lines.append(f"-- Generated by importer-v{importer_version}")
        self.dry_run_lines.append(f"-- Generated at: {datetime.utcnow().isoformat()}Z")
        self.dry_run_lines.append(f"-- Target: {target}")
        self.dry_run_lines.append("")

    def __enter__(self) -> "MysqlWriter":
        if self.target in ("local", "prod"):
            if pymysql is None:
                raise RuntimeError(
                    "pymysql necessário pra modo --target local|prod"
                )
            self.con = pymysql.connect(
                host=self.host,
                port=self.port,
                user=self.user,
                password=self.password,
                database=self.database,
                charset="utf8mb4",
                cursorclass=pymysql.cursors.DictCursor,
                autocommit=False,
            )
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        if self.target == "dry-run":
            # Salva SQL gerado em arquivo
            self.output_dir.mkdir(parents=True, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d-%H%M%S")
            path = self.output_dir / f"dry-run-{ts}.sql"
            path.write_text("\n".join(self.dry_run_lines), encoding="utf-8")
            print(f"💾 SQL salvo: {path} ({len(self.dry_run_lines)} linhas)")

        if self.con:
            if exc_type is None:
                self.con.commit()
            else:
                self.con.rollback()
            self.con.close()

    # ------------------------------------------------------------------------
    # UPSERT helpers
    # ------------------------------------------------------------------------

    def upsert_account(
        self,
        business_id: int,
        name: str,
        account_number: str,
        legacy_source: str,
        legacy_id: str,
        legacy_metadata: dict | None = None,
        is_closed: bool = False,
        account_type: str = "saving_current",
    ) -> int | None:
        """UPSERT em accounts (core) + accounts_legacy_map (bridge).

        Retorna account_id (real após commit, ou placeholder em dry-run).
        """
        # Step 1: lookup map pra ver se já existe
        existing_id = self._find_account_id_by_legacy(business_id, legacy_source, legacy_id)

        if existing_id is None:
            # INSERT em accounts
            sql_account = """
                INSERT INTO accounts (business_id, name, account_number, account_type, is_closed, created_at, updated_at)
                VALUES (%(business_id)s, %(name)s, %(account_number)s, %(account_type)s, %(is_closed)s, NOW(), NOW())
            """
            params = {
                "business_id": business_id,
                "name": name,
                "account_number": account_number,
                "account_type": account_type,
                "is_closed": 1 if is_closed else 0,
            }
            account_id = self._execute(sql_account, params, returning_id=True)

            # INSERT em accounts_legacy_map
            sql_map = """
                INSERT INTO accounts_legacy_map
                    (business_id, account_id, legacy_source, legacy_id,
                     legacy_imported_at, legacy_importer_version, legacy_metadata,
                     created_at, updated_at)
                VALUES
                    (%(business_id)s, %(account_id)s, %(legacy_source)s, %(legacy_id)s,
                     NOW(), %(importer_version)s, %(legacy_metadata)s,
                     NOW(), NOW())
            """
            self._execute(
                sql_map,
                {
                    "business_id": business_id,
                    "account_id": account_id or 0,
                    "legacy_source": legacy_source,
                    "legacy_id": legacy_id,
                    "importer_version": self.importer_version,
                    "legacy_metadata": json.dumps(legacy_metadata) if legacy_metadata else None,
                },
            )
            self.stats["inserts"] += 1
        else:
            # UPDATE — preserve ID, atualiza fields
            sql_update = """
                UPDATE accounts
                SET name = %(name)s,
                    account_number = %(account_number)s,
                    is_closed = %(is_closed)s,
                    updated_at = NOW()
                WHERE id = %(account_id)s
            """
            self._execute(
                sql_update,
                {
                    "name": name,
                    "account_number": account_number,
                    "is_closed": 1 if is_closed else 0,
                    "account_id": existing_id,
                },
            )
            self.stats["updates"] += 1
            account_id = existing_id

        return account_id

    def upsert_fin_conta_bancaria(
        self,
        business_id: int,
        account_id: int,
        legacy_source: str,
        legacy_id: str,
        banco_codigo: str,
        agencia: str,
        agencia_dv: str | None,
        conta_dv: str | None,
        carteira: str,
        convenio: str | None,
        codigo_cedente: str | None,
        beneficiario_documento: str,
        beneficiario_razao_social: str,
        ativo_para_boleto: bool,
        metadata: dict | None,
    ) -> None:
        """UPSERT em fin_contas_bancarias (módulo Financeiro)."""
        sql = """
            INSERT INTO fin_contas_bancarias
                (business_id, account_id, banco_codigo, agencia, agencia_dv, conta_dv,
                 carteira, convenio, codigo_cedente,
                 beneficiario_documento, beneficiario_razao_social,
                 ativo_para_boleto, metadata,
                 legacy_source, legacy_id, legacy_imported_at,
                 created_at, updated_at)
            VALUES
                (%(business_id)s, %(account_id)s, %(banco_codigo)s, %(agencia)s, %(agencia_dv)s, %(conta_dv)s,
                 %(carteira)s, %(convenio)s, %(codigo_cedente)s,
                 %(beneficiario_documento)s, %(beneficiario_razao_social)s,
                 %(ativo)s, %(metadata)s,
                 %(legacy_source)s, %(legacy_id)s, NOW(),
                 NOW(), NOW())
            ON DUPLICATE KEY UPDATE
                banco_codigo = VALUES(banco_codigo),
                agencia = VALUES(agencia),
                agencia_dv = VALUES(agencia_dv),
                conta_dv = VALUES(conta_dv),
                carteira = VALUES(carteira),
                convenio = VALUES(convenio),
                codigo_cedente = VALUES(codigo_cedente),
                beneficiario_documento = VALUES(beneficiario_documento),
                beneficiario_razao_social = VALUES(beneficiario_razao_social),
                ativo_para_boleto = VALUES(ativo_para_boleto),
                metadata = VALUES(metadata),
                legacy_imported_at = NOW(),
                updated_at = NOW()
        """
        params = {
            "business_id": business_id,
            "account_id": account_id,
            "banco_codigo": banco_codigo,
            "agencia": agencia,
            "agencia_dv": agencia_dv,
            "conta_dv": conta_dv,
            "carteira": carteira,
            "convenio": convenio,
            "codigo_cedente": codigo_cedente,
            "beneficiario_documento": beneficiario_documento,
            "beneficiario_razao_social": beneficiario_razao_social,
            "ativo": 1 if ativo_para_boleto else 0,
            "metadata": json.dumps(metadata) if metadata else None,
            "legacy_source": legacy_source,
            "legacy_id": legacy_id,
        }
        self._execute(sql, params)

    # ------------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------------

    def _find_account_id_by_legacy(
        self, business_id: int, legacy_source: str, legacy_id: str
    ) -> int | None:
        """Lookup em accounts_legacy_map. Retorna None se não existe ou em dry-run."""
        if self.target == "dry-run":
            return None  # dry-run sempre simula INSERT

        if self.con is None:
            return None

        with self.con.cursor() as cur:
            cur.execute(
                """
                SELECT account_id FROM accounts_legacy_map
                WHERE business_id = %s AND legacy_source = %s AND legacy_id = %s
                """,
                (business_id, legacy_source, legacy_id),
            )
            row = cur.fetchone()
            return row["account_id"] if row else None

    def _execute(self, sql: str, params: dict, returning_id: bool = False) -> int | None:
        """Executa ou imprime (dry-run)."""
        formatted = self._format_sql_for_log(sql, params)

        if self.target == "dry-run":
            self.dry_run_lines.append(formatted + ";")
            self.dry_run_lines.append("")
            return 999999 if returning_id else None  # placeholder em dry-run

        if self.con is None:
            raise RuntimeError("Conexão MySQL não aberta")

        with self.con.cursor() as cur:
            cur.execute(sql, params)
            if returning_id:
                return cur.lastrowid
        return None

    @staticmethod
    def _format_sql_for_log(sql: str, params: dict) -> str:
        """Formata SQL com params inline pra log/dry-run (não usar em produção real)."""
        sql_clean = " ".join(sql.split())
        for key, value in params.items():
            if value is None:
                replacement = "NULL"
            elif isinstance(value, (int, float)):
                replacement = str(value)
            elif isinstance(value, str):
                escaped = value.replace("'", "''")
                replacement = f"'{escaped}'"
            else:
                replacement = f"'{value}'"
            sql_clean = sql_clean.replace(f"%({key})s", replacement)
        return sql_clean
