// resources/js/Pages/Fiscal/_lib/debitos-conhecidos.ts
// GERADO por scripts/governance/fiscal-debitos-derive.mjs — NÃO editar à mão.
// Fonte: os bullets [BACKLOG] dos sete resources/js/Pages/Fiscal/<Tela>.casos.md.
// Pagou a dívida? Tache o bullet ([~~BACKLOG~~ ...]) e rode:
//   node scripts/governance/fiscal-debitos-derive.mjs --write

export type TomDebito = 'danger' | 'warning' | 'info';

export interface DebitoConhecido {
  /** A `route` da tela dona (o mesmo id de _lib/paginas-fiscais). */
  tela: string;
  tom: TomDebito;
  /** Os segmentos do marcador do bullet, sem emoji (ex.: `sem teste · débito de schema`). */
  rotulo: string;
  titulo: string;
  texto: string;
  /** true = o item espera decisão [W]; é o subconjunto do bloco de decisão pendente. */
  decisao: boolean;
  /** O `<Tela>.casos.md` de onde este item saiu (arquivo, não `arquivo:linha`). */
  ancora: string;
}

export const DEBITOS_CONHECIDOS: readonly DebitoConhecido[] = [
  { tela: "fiscal", tom: "warning", decisao: false, ancora: "Cockpit.casos.md",
    rotulo: "sem teste",
    titulo: "A série de 14 dias sai de uma consulta agrupada, sem repetição por dia",
    texto: "Dado emissões nas últimas duas semanas · Quando a série é montada · Então há um ponto por dia por status, calculado de uma vez só. Anti-hook do charter; sem teste dedicado." },
  { tela: "fiscal", tom: "warning", decisao: false, ancora: "Cockpit.casos.md",
    rotulo: "sem teste",
    titulo: "O faturamento aparece formatado em moeda brasileira",
    texto: "comportamento só de frontend, sem cobertura de Feature." },
  { tela: "fiscal", tom: "warning", decisao: false, ancora: "Cockpit.casos.md",
    rotulo: "sem teste",
    titulo: "Filtros, visões salvas, densidade e seleção em lote da tabela unificada",
    texto: "a fonte real chegou em 2026-09-02 (UC-FCKP-07); vira contrato quando alguém escrever o teste de filtro/visão/densidade sobre ela." },
  { tela: "nfe", tom: "warning", decisao: false, ancora: "Nfe.casos.md",
    rotulo: "sem teste",
    titulo: "Lista deferida filtra por tab/status/busca com paginação 50",
    texto: "rows é Inertia::defer; sem teste do payload filtrado (buildRowsPayload, ordem emitido_em DESC)." },
  { tela: "nfe", tom: "warning", decisao: false, ancora: "Nfe.casos.md",
    rotulo: "sem teste",
    titulo: "Retransmitir só aceita nota rejeitada/denegada/erro_envio",
    texto: "Dado nota em outro status · Quando pede retransmissão · Então volta com erro sem chamar o Service. Não é testável sem banco: no AcoesController::retransmitir a whitelist é checada depois do firstOrFail(), logo exige nfe_emissoes — indisponível nas duas lanes de hoje (ver §recibo). O caso que existia aqui assertava um array literal escrito no próprio teste e foi removido em 2026-07-28 (não defendia nada). Parcialmente coberto desde 2026-09-01 pelo UC-FNFE-09, que prova estaticamente que a whitelist do Service é exatamente essa e que ela rejeita — o que falta aqui é o caminho de runtime, e ele segue esperando lane com as migrations do NfeBrasil." },
  { tela: "nfe", tom: "info", decisao: false, ancora: "Nfe.casos.md",
    rotulo: "parcialmente coberto",
    titulo: "Drawer: mapa \"Jana sugere\" por cstat rejeitado, pílula temporal na linha",
    texto: "comportamento de UI, sem cobertura Feature nem E2E (a tela não aparece em tests/Browser). Reduzido em 2026-09-03: a metade \"atalhos J/K + Enter\" saiu deste item e virou UC-FNFE-10, com teste de render que morde (4 mutações provadas). O que fica aqui é o que segue descoberto: o mapa guiado por cstat e a pílula temporal." },
  { tela: "nfse", tom: "warning", decisao: false, ancora: "Nfse.casos.md",
    rotulo: "sem teste",
    titulo: "Os chips filtram por estado da nota de serviço",
    texto: "autorizadas, rejeitadas, em processamento (rascunho + processando), canceladas. Existe no Controller; sem teste do resultado filtrado." },
  { tela: "nfse", tom: "warning", decisao: false, ancora: "Nfse.casos.md",
    rotulo: "sem teste",
    titulo: "A busca aceita número, código de verificação, nome e documento do tomador",
    texto: "sem teste do resultado." },
  { tela: "nfse", tom: "warning", decisao: false, ancora: "Nfse.casos.md",
    rotulo: "sem teste",
    titulo: "O filtro de competência restringe as linhas ao mês escolhido",
    texto: "só o caminho de mês inválido tem teste; o caminho feliz não." },
  { tela: "nfse", tom: "warning", decisao: false, ancora: "Nfse.casos.md",
    rotulo: "sem teste · débito de schema",
    titulo: "O município da prestação aparece na linha",
    texto: "a coluna não existe no schema em produção (duelo de duas migrations para a mesma tabela, resolvido revertendo o Controller para o schema antigo e traduzindo os estados). Hoje o campo volta vazio por desenho. Ver SDD §5.2." },
  { tela: "dfe", tom: "warning", decisao: false, ancora: "Dfe.casos.md",
    rotulo: "em revisão",
    titulo: "Nenhuma manifestação chegava à SEFAZ, por nenhum caminho",
    texto: "ManifestacaoService::buildConfig() e DistribuicaoDfeService::buildConfig() fazem select(['name','tax_number_1','state']) em business. A coluna state não existe: 133 colunas no schema canônico (database/schema/mysql-schema.sql), 133 no staging CT 100 e 133 em produção Hostinger, sem state nos três — e nenhuma das 43 migrations que tocam business a cria. Toda manifestação morre em SQLSTATE[42S22] Unknown column 'state', incluindo o ManifestacaoController::bulkConfirmar do próprio NfeBrasil. Os dois sites já carregam ?? 'SP', e o docblock diz *\"UF default 35 (SP) — manifestação é nacional, mas Tools exige cUF\"* — o default parece ter sido sempre a intenção, e a coluna no select o acidente. Era motor fiscal, e a decisão [W] veio em 2026-09-04: consertar pelo resolverUF canônico. Feito no PR #6748, nos dois sites (a lápide §5 2026-08-02 é explícita sobre corrigir só um de N) — e ali apareceram mais dois defeitos empilhados atrás deste. O #6748 mergeou em 2026-09-04 13:59 — o item fica aqui até esta tela ganhar um UC que prove a manifestação ponta-a-ponta, que é o que falta para ele sair de vez." },
  { tela: "dfe", tom: "warning", decisao: false, ancora: "Dfe.casos.md",
    rotulo: "sem teste",
    titulo: "O prazo aparece com três níveis de urgência, vindo do prazo que a SEFAZ calculou",
    texto: "Dado uma nota recebida com prazo definido · Quando a contadora lê a linha · Então vê quantos dias restam, sinalizado como crítico, atenção ou tranquilo. O charter é explícito: a fonte de verdade é o prazo gravado pela SEFAZ, não um \"90 dias\" fixo no código. O cálculo existe; nenhum teste valida os níveis." },
  { tela: "dfe", tom: "warning", decisao: false, ancora: "Dfe.casos.md",
    rotulo: "sem teste",
    titulo: "Os chips filtram por estado de manifestação",
    texto: "pendentes (pendente + ciência), confirmadas, desconhecidas, não realizadas, todas. Existe no Controller; sem teste do resultado." },
  { tela: "dfe", tom: "warning", decisao: false, ancora: "Dfe.casos.md",
    rotulo: "sem teste",
    titulo: "A busca aceita chave, CNPJ do emitente e nome do emitente",
    texto: "inclusive digitando o CNPJ com pontuação. Sem teste do resultado." },
  { tela: "dfe", tom: "warning", decisao: true, ancora: "Dfe.casos.md",
    rotulo: "sem teste",
    titulo: "A aba Histórico mostra manifestações reais",
    texto: "hoje ela é servida por dado de demonstração com ator e observação inventados (CU-FISC-16 do SDD §6.5 · §5.4.1). A consulta real está declarada como pendência no próprio código. Precisa de decisão [W] sobre marcar procedência, esconder atrás de flag ou declarar Non-Goal." },
  { tela: "fiscal_eventos", tom: "warning", decisao: false, ancora: "Eventos.casos.md",
    rotulo: "sem teste",
    titulo: "A justificativa exibida é truncada, para não vazar PII do XML",
    texto: "Dado um evento com justificativa longa · Quando a linha renderiza · Então só um trecho inicial aparece. Anti-hook do charter (o texto do motivo da SEFAZ pode conter dado pessoal); o corte existe no Controller, sem teste." },
  { tela: "fiscal_eventos", tom: "warning", decisao: false, ancora: "Eventos.casos.md",
    rotulo: "sem teste",
    titulo: "Filtro por categoria e por janela de tempo",
    texto: "7, 30 ou 90 dias, com 30 como padrão. Existe no Controller; sem teste do resultado." },
  { tela: "fiscal_eventos", tom: "warning", decisao: false, ancora: "Eventos.casos.md",
    rotulo: "sem teste",
    titulo: "A nota de origem vem junto sem multiplicar consultas",
    texto: "o charter limita a um relacionamento carregado; nenhum teste guarda esse limite." },
  { tela: "fiscal_eventos", tom: "info", decisao: false, ancora: "Eventos.casos.md",
    rotulo: "coberto em outra tela",
    titulo: "As ações que GERAM evento",
    texto: "(cancelamento, carta de correção, inutilização, retransmissão, manifestação) têm contrato em Nfe.casos.md (UC-FNFE-04..07) e Dfe.casos.md (UC-FDFE-03/04) — o dispatch vive lá, esta tela só lê o resultado. Não se duplica UC entre telas irmãs." },
  { tela: "fiscal_config", tom: "warning", decisao: false, ancora: "Config.casos.md",
    rotulo: "sem teste",
    titulo: "A validade do certificado aparece com três tons de urgência",
    texto: "vencido, perto de vencer (até 30 dias) e tranquilo. O cálculo existe no Controller; sem teste dos limiares." },
  { tela: "fiscal_config", tom: "warning", decisao: false, ancora: "Config.casos.md",
    rotulo: "sem teste",
    titulo: "O painel mostra regime, série, próximo número e tributação padrão",
    texto: "leitura consolidada do que o NfeBrasil guarda. Sem teste; note que esses dados são lidos por consulta direta à tabela, fora do escopo automático de business — o escopo é aplicado à mão a partir da sessão (SDD §5.2)." },
  { tela: "fiscal_config", tom: "warning", decisao: true, ancora: "Config.casos.md",
    rotulo: "sem teste",
    titulo: "A aba de séries mostra séries reais",
    texto: "hoje ela é servida por dado de demonstração com uma filial inventada (CU-FISC-16 do SDD §6.5 · §5.4.1). Precisa de decisão [W]." },
  { tela: "fiscal_config", tom: "warning", decisao: true, ancora: "Config.casos.md",
    rotulo: "sem campo",
    titulo: "Cadastrar o e-mail do contador",
    texto: "a linha existe no card (UC-FCFG-05) declarando a ausência. Dar valor a ela exige coluna nova em nfe_business_configs (migration em PR próprio, nunca junto de UI) e a decisão de se o envio ao contador é cópia automática de toda nota ou digest. Sem contrato até [W] decidir." },
  { tela: "fiscal_config", tom: "warning", decisao: true, ancora: "Config.casos.md",
    rotulo: "sem campo",
    titulo: "Ligar/desligar o envio automático POR EMPRESA",
    texto: "hoje as duas chaves são de deploy (Modules/NfeBrasil/Config/config.php), e o card diz isso. Tornar por-tenant é coluna nova + tela editável, não ajuste de leitura." },
  { tela: "fiscal_config", tom: "info", decisao: false, ancora: "Config.casos.md",
    rotulo: "coberto em outra tela",
    titulo: "O bloqueio do download de SPED por feature flag",
    texto: "tem contrato em Sped.casos.md (UC-FSPED-05) — a aba \"sped\" desta tela apenas aponta para lá." },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "source-grep",
    titulo: "TXT traz os 23 registros canônicos dos Blocos 0+C+E+H+9",
    texto: "SpedIcmsIpiGeneratorServiceTest::contract: 23 registros canon procura os NOMES DE MÉTODO (registro0000…) no fonte e conta um array literal escrito no próprio teste. Não gera arquivo nem valida linha |REG|…|." },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "source-grep",
    titulo: "Bloco E: E110 consolida os débitos do C190 e E116 só sai com ICMS a recolher",
    texto: "os dois casos assertam toContain(\"array_sum(array_column(...))\") e toContain(\"if ($vlTotalDebitos > 0)\") no fonte." },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "source-grep",
    titulo: "Bloco H é esqueleto (IND_MOV=1)",
    texto: "asserta toContain('registroH001(1)') no fonte; o inventário real exige integração Stock/ProductCatalogue (declaração de 31/12)." },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "source-grep",
    titulo: "Span OTel fiscal.sped.gerar",
    texto: "grep da string no fonte." },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "sem teste",
    titulo: "Panorama das 5 competências",
    texto: "mês, notas autorizadas, valor, status (aberto/pronto/entregue) e prazo. SpedController::index agrega; nenhum teste asserta o payload das 5 competências. (O gate do export deixou de ser só \"tem notas?\" em 2026-09-03: agora são as 4 checagens do UC-FSF1-03 mais a contagem de notas, e as checagens têm teste. O que segue sem teste é a agregação em si.) (O prazo exibido usa dia 15 como heurística; o prazo legal da EFD é fixado por cada UF.)" },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "sem teste",
    titulo: "Smoke PVA-EFD homologação CONFAZ",
    texto: "importar o TXT no validador oficial sem erro estrutural. (O golden file passou a existir em 2026-09-03 — UC-FSF1-05 —, e ele confere estrutura, blocos e contadores. O que continua sem prova é a importação no PVA-EFD real, que é ferramenta externa; e o golden já expõe dois motivos pelos quais o PVA recusaria hoje: CNPJ/IE vazios e UF fixa. Ver o aviso no UC-FSF1-05.)" },
  { tela: "sped", tom: "warning", decisao: false, ancora: "Sped.casos.md",
    rotulo: "sem teste",
    titulo: "Entradas (DF-e manifestada), EFD-Contribuições (PIS/COFINS) e saldo credor anterior real no E110",
    texto: "Non-Goals declarados; nenhum código nem teste." },
];
